import type { Recommendation } from "@/types/recommendation";

const BASE: Omit<Recommendation, "id" | "slug" | "category" | "name" | "tagline" | "sort_order"> = {
  description: null,
  why_we_love_it: null,
  address: null,
  lat: null,
  lng: null,
  website: null,
  phone: null,
  opening_hours: null,
  price_range: null,
  walk_time_min: null,
  bike_time_min: null,
  bus_route: null,
  season: [],
  tags: [],
  image_url: null,
  image_credit: null,
  source_url: null,
  google_place_id: null,
  image_reference: null,
  image_attribution: null,
  published: true,
  created_at: "",
  updated_at: "",
};

export const RECOMMENDATIONS: Recommendation[] = [
  // ── EAT ────────────────────────────────────────────────────────────────
  {
    ...BASE,
    id: 1, slug: "two-hands", category: "eat", sort_order: 10,
    image_url: "/images/recommendations/two-hands.jpg",
    name: "Two Hands",
    tagline: "Creative cosmopolitan cuisine — great for brunch",
    address: "Waldstätterstrasse 6, 6003 Luzern",
    lat: 47.0519, lng: 8.2957,
    website: "https://www.twohandsluzern.ch",
    price_range: 2,
    description: "Two Hands is our go-to for brunch in Lucerne. The menu is creative and cosmopolitan — think seasonal ingredients put together with care, in a relaxed setting that doesn't feel rushed. It gets busy on weekend mornings, so arriving early or on a weekday is worth it. The chai tea and homemade pancakes are a good reason to come back.",
    bus_route: "Take bus no. 14 to Moosmatt, then walk 4 minutes to Neustadt.",
    why_we_love_it: "Chai tea and homemade pancakes",
    tags: ["personal-favorites", "brunch"],
  },
  {
    ...BASE,
    id: 2, slug: "melissas-kitchen", category: "eat", sort_order: 20,
    image_url: "/images/recommendations/melissas-kitchen.jpg",
    name: "Melissa's Kitchen",
    tagline: "Homemade, fresh, organic — brunch on Sundays",
    address: "Hirschengraben 19, 6003 Luzern",
    website: "https://www.melissaskitchen.ch",
    price_range: 1,
    description: "Melissa's Kitchen in Lucerne delights guests with homemade, fresh, and healthy dishes inspired by international flavors. Here, creative cuisine meets warm hospitality. Whether breakfast, lunch, or afternoon cake, everything is prepared with love, often using regional and organic ingredients. The cozy atmosphere invites you to linger and makes Melissa's Kitchen a place where enjoyment, quality, and a feel-good atmosphere harmonize perfectly.",
    bus_route: "Take bus no. 14 to Pilatusplatz, then walk for 5 minutes.",
    why_we_love_it: "On Sundays and public holidays, there is a large, delicious brunch buffet.",
    tags: ["brunch"],
  },
  {
    ...BASE,
    id: 3, slug: "karls-kraut", category: "eat", sort_order: 30,
    image_url: "/images/recommendations/karls-kraut.jpg",
    name: "Karls Kraut",
    tagline: "Vegan cuisine",
    address: "St. Karliquai 7, 6004 Luzern",
    website: "https://www.karlskraut.ch",
    phone: "+41 41 534 77 77",
    price_range: 2,
    description: "Karls Kraut in Lucerne stands for creative, plant-based cuisine full of flavor and variety. Here, fresh, seasonal ingredients are transformed into colorful bowls, sophisticated vegetable dishes, and homemade specialties – all vegetarian or vegan. The charming, cozy atmosphere invites you to linger, while the changing menu always has new culinary surprises in store. Karls Kraut is the perfect place for conscious enjoyment that is healthy, sustainable, and simply delicious.",
    bus_route: "Take bus no. 14 to Pilatusplatz, then walk 10 minutes to the old town, past Mühlenplatz and along the Reuss river.",
    why_we_love_it: "Brunch is served every second and fourth Sunday of the month and is very delicious.",
    tags: ["vegetarian", "brunch"],
  },
  {
    ...BASE,
    id: 4, slug: "pastarazzi-himmelrich", category: "eat", sort_order: 40,
    image_url: "/images/recommendations/pastarazzi-himmelrich.jpg",
    name: "Pastarazzi Himmelrich",
    tagline: "Great pizza & pasta",
    address: "Claridenstrasse 2, 6003 Luzern",
    website: "https://www.pastarazzi.ch",
    phone: "+41 41 662 46 84",
    price_range: 2,
    description: "Pastarazzi in Himmelrich, Lucerne, is all about fresh, handmade pasta in lots of creative ways. They cook with high-quality, often local ingredients every day—from classic recipes to surprising new creations. The modern, cozy atmosphere invites you to linger, while the open kitchen and warm service ensure an authentic experience. Whether for a quick lunch or a relaxed dinner, Pastarazzi combines Italian culinary culture with Lucerne charm.",
    bus_route: "Take bus no. 14 to the Paulusplatz bus stop, then walk 4 minutes to Neustadt.",
    why_we_love_it: "Seasonal ravioli mix",
  },
  {
    ...BASE,
    id: 5, slug: "nooch-mattenhof", category: "eat", sort_order: 50,
    image_url: "/images/recommendations/nooch-mattenhof.jpg",
    name: "Nooch Mattenhof",
    tagline: "Asian street food & sushi",
    address: "Am Mattenhof 16a, 6010 Kriens",
    website: "https://www.nooch.ch",
    price_range: 2,
    description: "Nooch is a ten-minute walk from the apartment — one of the easiest dinner options if you don't feel like taking the bus. Asian street food: sushi, curries, noodle and rice bowls. The Mattenhof complex it sits in is new and modern. Good for a relaxed evening out without going all the way into Lucerne.",
    bus_route: "It is a 10-minute walk from Mattenhof station in Kriens.",
    why_we_love_it: "Infused Water \"Phoenix and Passion\" and the sushi",
  },
  {
    ...BASE,
    id: 6, slug: "majorelle-neustadt", category: "eat", sort_order: 60,
    image_url: "/images/recommendations/majorelle-neustadt.jpg",
    name: "Majorelle Neustadt",
    tagline: "Moroccan cuisine",
    address: "Himmelrichstrasse 12, 6003 Luzern",
    price_range: 2,
    description: "Moroccan restaurant in Neustadt, a short bus ride from the apartment. Tagines, couscous, and mezze — the mezze platter for sharing is our recommendation if you're going with someone. The interior is warm and atmospheric. Good for an evening out that feels a bit different from the usual Swiss options.",
    bus_route: "Take bus no. 14 to the Paulusplatz bus stop, then walk 4 minutes to Neustadt.",
    why_we_love_it: "The mezze platter for sharing",
  },
  {
    ...BASE,
    id: 7, slug: "rest-helvetia", category: "eat", sort_order: 70,
    image_url: "/images/recommendations/restaurant-helvetia.jpg",
    name: "Rest. Helvetia",
    tagline: "Swiss classics",
    address: "Waldstätterstrasse 9, 6003 Luzern",
    website: "https://www.helvetialuzern.ch",
    phone: "+41 41 210 44 50",
    price_range: 2,
    description: "The Helvetia restaurant in Lucerne combines traditional Swiss cuisine with contemporary sophistication. The focus here is on classics such as rösti and fresh fish dishes – prepared with regional ingredients and great attention to detail. The stylish, cozy atmosphere invites both locals and visitors to linger. With its warm service and select wine list, Helvetia is a place for authentic enjoyment and convivial moments in the heart of Lucerne.",
    bus_route: "Take bus no. 14 to Moosmatt, then walk 3 minutes to Neustadt.",
    why_we_love_it: "Farmhouse bratwurst and chocolate mousse — a local meeting point in the Helvetia-Park",
  },
  {
    ...BASE,
    id: 8, slug: "wirtshaus-taube", category: "eat", sort_order: 80,
    image_url: "/images/recommendations/wirtshaus-taube.jpg",
    name: "Wirtshaus Taube",
    tagline: "Lucerne recipes & Swiss classics",
    address: "Burgerstrasse 3, 6003 Luzern",
    lat: 47.0521, lng: 8.3048,
    website: "https://www.taube-luzern.ch",
    phone: "+41 41 210 07 47",
    price_range: 2,
    description: "The Wirtshaus Taube in Lucerne stands for genuine hospitality and honest, down-to-earth cuisine. Seasonal specialities, Swiss classics and fine home-style dishes are served in a cosy, rustic atmosphere – always freshly prepared and often using regional products. Whether for lunch, dinner, or a get-together with friends, the Traube offers a warm, inviting atmosphere where you will immediately feel at home. Here, tradition meets warmth—a piece of Lucerne's way of life.",
    bus_route: "Take bus no. 14 to Pilatusplatz, then walk 5 minutes toward the Reuss River.",
    why_we_love_it: "Lucerne Kügelipastetli — and a terrace right on the Reuss on sunny days",
    tags: ["personal-favorites", "view"],
  },
  {
    ...BASE,
    id: 9, slug: "mamma-leone", category: "eat", sort_order: 90,
    image_url: "/images/recommendations/mamma-leone.jpg",
    name: "Mamma Leone",
    tagline: "Italian · 14 Gault Millau points",
    address: "Mühlenplatz 12, 6004 Luzern",
    website: "https://www.mammaleone-luzern.ch",
    phone: "+41 41 410 17 91",
    price_range: 3,
    description: "Mamma Leone in Lucerne brings the authentic taste of Italy to your plate. Fresh pasta, crispy stone-baked pizzas, and homemade desserts are prepared with the finest ingredients and lots of amore. The Mediterranean atmosphere, friendly service, and exquisite wine selection invite you to linger—whether for a relaxed lunch, a romantic dinner, or a cheerful get-together with friends. Mamma Leone is a piece of Italy in the heart of Lucerne that combines enjoyment and joie de vivre. 14 Gault Millau points",
    bus_route: "Take bus no. 14 to Pilatusplatz, then walk 8 minutes to the old town.",
    why_we_love_it: "Carpaccio di barbabietola (beetroot carpaccio with burrata)",
    tags: ["view"],
  },
  {
    ...BASE,
    id: 10, slug: "rest-bayts", category: "eat", sort_order: 100,
    image_url: "/images/recommendations/rest-bayts.jpg",
    name: "Rest. Bayt's",
    tagline: "Vegan fine dining",
    address: "Bireggstrasse 24, 6003 Luzern",
    website: "https://www.bayts.ch",
    phone: "+41 41 544 95 27",
    price_range: 3,
    description: "Bayts in Lucerne offers purely plant-based culinary experiences of the highest standard. A multi-course menu showcasing vegetables in creative ways is served in an elegant yet relaxed atmosphere. The dishes surprise with sophisticated flavor combinations, accompanied by carefully selected wines or non-alcoholic pairings. Seasonal ingredients, friendly service, and a personal touch make Bayts a hotspot for modern, sustainable fine dining in the heart of Lucerne.",
    bus_route: "Take bus no. 14 to Paulusplatz, then walk toward Pauluskirche and turn left into the neighborhood.",
    why_we_love_it: "Let yourself be surprised",
    tags: ["vegetarian", "splurge"],
  },
  {
    ...BASE,
    id: 12, slug: "rest-fed", category: "eat", sort_order: 120,
    image_url: "/images/recommendations/rest-fed.jpg",
    name: "Rest. FED",
    tagline: "Food-sharing experience",
    address: "Pilatusstrasse 46, 6003 Luzern",
    website: "https://www.fed-restaurant.ch",
    phone: "+41 41 240 87 23",
    price_range: 3,
    description: "FED in Lucerne combines modern design with innovative cuisine and a food-sharing concept. The restaurant focuses on fresh, regional ingredients and uses them to create creative dishes with international influences. Whether for a relaxed lunch, a stylish dinner, or cocktails at the bar, FED offers a culinary experience in an urban, elegant atmosphere. The open kitchen and attentive service make every visit special. A meeting place for connoisseurs who appreciate good food, a stylish ambience, and lively hospitality.",
    bus_route: "Take bus no. 14 to Pilatusplatz, then walk 3 minutes across the intersection.",
    why_we_love_it: "Homemade cherry lemonade",
    tags: ["splurge"],
  },
  {
    ...BASE,
    id: 13, slug: "grottino-1313", category: "eat", sort_order: 130,
    image_url: "/images/recommendations/grottino-1313.jpg",
    name: "Grottino 1313",
    tagline: "Surprise menu, Mediterranean — unique atmosphere",
    address: "Industriestrasse 7, 6005 Luzern",
    lat: 47.0393, lng: 8.3063,
    website: "https://www.grottino1313.ch",
    phone: "+41 41 610 13 13",
    price_range: 3,
    description: "Grottino 1313 in Lucerne is a culinary gem with charming industrial charm. There is no fixed menu here – whatever is in season and available at the market is what is cooked. Mediterranean-inspired dishes, fresh and prepared with love, are served in a convivial atmosphere at long wooden tables. Grottino stands for shared enjoyment, honest cuisine, and warm hospitality. It's a place where you feel like you're among friends and are surprised every time you visit.",
    bus_route: "Take bus no. 14 to Kantonalbank, walk 2 minutes to the next bus stop (around the corner on the right), then take bus no. 6, 7, 8, or 21 to Werkhofstrasse, and walk 4 minutes to the restaurant.",
    why_we_love_it: "This Mediterranean restaurant offers a 4 or 5-course surprise menu in tavolata style. It is always very busy, so reservations are recommended.",
    tags: ["personal-favorites"],
  },
  {
    ...BASE,
    id: 14, slug: "jazzkantine", category: "eat", sort_order: 140,
    image_url: "/images/recommendations/jazzkantine.jpg",
    name: "Jazzkantine",
    tagline: "Tavolata, music & cocktails",
    address: "Grabenstrasse 8, 6002 Luzern",
    website: "https://www.jazzkantine.ch",
    price_range: 2,
    description: "Right in the old town — the Jazzkantine is a relaxed spot for an evening out with live music, cocktails, and a rotating programme. Good vegetarian options on the menu. Worth checking their schedule before you go.",
    bus_route: "In the old town; the Jazzkantine offers delicious lunch menus or sourdough bread with spreads for a quick bite!",
    why_we_love_it: "Sourdough bread with spread",
    tags: ["evening"],
  },
  {
    ...BASE,
    id: 15, slug: "himmelrich-terrace", category: "eat", sort_order: 150,
    image_url: "/images/recommendations/himmelrich-terrace.jpg",
    name: "Himmelrich Terrace",
    tagline: "Terrace with lake views",
    address: "Schattenbergstrasse 107, 6010 Kriens",
    website: "https://hotel-himmelrich.ch",
    phone: "+41 41 557 40 07",
    price_range: 2,
    description: "Worth going on a clear day — take the walk up through the Himmelrich neighbourhood, have lunch or a drink on the terrace, and enjoy the views over the city. Seasonal dishes, salads, bowls. The terrace is the reason to come; the walk there and back makes it a proper outing.",
    bus_route: "Accessible by car via Kriens, or on foot up the Pilatus, approx. 30 minutes.",
    why_we_love_it: "The view from the terrace is magnificent.",
    tags: ["view", "sunny-day"],
  },

  // ── DRINK ───────────────────────────────────────────────────────────────
  {
    ...BASE,
    id: 20, slug: "suite-rooftop", category: "drink", sort_order: 10,
    image_url: "/images/recommendations/suite-rooftop.jpg",
    name: "Suite Rooftop",
    tagline: "Stylish rooftop bar · lake and mountain views",
    address: "Pilatusstrasse 3, 6003 Luzern",
    lat: 47.0506, lng: 8.3085,
    website: "https://www.suite-luzern.ch",
    price_range: 3,
    description: "A rooftop bar on top of the Hotel The Suite, with open views over the lake and the city. Cocktails and wine, a relaxed crowd, and good music in the evening. Worth going once — especially on a clear summer evening when the light is right. Can get busy on weekends; arriving early helps.",
    bus_route: "Directly at the train station, above Starbucks.",
    why_we_love_it: "Whiskey Sour",
    tags: ["personal-favorites", "view", "evening"],
  },
  {
    ...BASE,
    id: 21, slug: "montana-beach-club", category: "drink", sort_order: 20,
    image_url: "/images/recommendations/montana-beach-club.jpg",
    name: "Montana Beach Club",
    tagline: "Elegant · Art Deco Hotel Montana rooftop · open views over the lake",
    address: "Adligenswilerstrasse 22, 6006 Luzern",
    website: "https://www.hotel-montana.ch",
    phone: "+41 41 419 00 00",
    price_range: 3,
    description: "The Montana Beach Club in Lucerne combines a vacation feeling with spectacular views of Lake Lucerne and the Alps. On the roof terrace of the Art Deco Hotel Montana, guests can enjoy comfortable lounges, cool drinks, refreshing cocktails, and summer snacks. Sand under your feet, relaxing music, and sparkling water create a unique atmosphere in the middle of the city. Whether for sunbathing during the day or sundowners in the evening, the Montana Beach Club is an exclusive hotspot for summer enjoyment.",
    bus_route: "Take bus no. 14 to Gärtnerstrasse, then walk down Abendweg for 5 minutes. Or change at Lucerne train station to bus no. 8 or 6 to Lucerne Casino-Palace, where you will find the lift directly to the Montana on the other side of the street.",
    why_we_love_it: "The fantastic mocktails",
    tags: ["view", "sunset"],
  },
  {
    ...BASE,
    id: 22, slug: "sunset-bar", category: "drink", sort_order: 30,
    image_url: "/images/recommendations/sunset-bar.jpg",
    name: "Sunset Bar",
    tagline: "Outdoor · lake & mountain views",
    address: "Seeburgstrasse 61, 6006 Luzern",
    website: "https://www.sunsetbar.ch",
    price_range: 2,
    description: "Outdoor bar on the lake at Hotel Seeburg, east of the old town. Best visited in the evening — the light over the mountains and the water is hard to beat. Open in summer. Cocktails, wine, and light snacks.",
    bus_route: "This location is outdoors. There are various seating options and snack stands. The Sunset Bar is located directly on the lake with a view of the mountains.",
    why_we_love_it: "Mojito",
    tags: ["lake", "sunset"],
  },
  {
    ...BASE,
    id: 23, slug: "central-kriens", category: "drink", sort_order: 40,
    image_url: "/images/recommendations/central-kriens.jpg",
    name: "Central Kriens",
    tagline: "Coffee & drinks · right next to the Pilatus gondola",
    address: "Waldheimstrasse 1, 6010 Kriens",
    website: "https://www.centralkriens.ch",
    price_range: 1,
    description: "A good stop after coming down from Pilatus — the restaurant and bar sits just a few minutes from the gondola base station in Kriens. Seasonal dishes, Swiss classics, and a few international options. Relaxed atmosphere, friendly service.",
    bus_route: "Walk 5 minutes to the Sternmatt bus stop, take bus no. 16 or 21 to the Busschleife stop. The restaurant is located across the street on the corner.",
    why_we_love_it: "Gin Tea",
    tags: [],
  },

  // ── CULTURE (Sport & Activities) ────────────────────────────────────────
  {
    ...BASE,
    id: 31, slug: "city-boulder", category: "culture", sort_order: 20,
    image_url: "/images/recommendations/city-boulder.jpg",
    name: "City Boulder",
    tagline: "Bouldering hall",
    website: "https://www.cityboulder.ch",
    phone: "+41 41 310 54 90",
    price_range: 2,
    description: "City Boulder in Kriens is the perfect place for anyone who wants to experience climbing without ropes in an urban atmosphere. The modern bouldering hall offers varied routes for beginners to professionals, regular new challenges, and a welcoming community. With a cozy lounge, snacks, and drinks, the sport also becomes a social experience. Whether for a quick workout or an entire afternoon, City Boulder combines exercise, fun, and community at the highest level.",
    bus_route: "Cross the street.",
  },
  {
    ...BASE,
    id: 33, slug: "cinema-bourbaki", category: "culture", sort_order: 40,
    image_url: "/images/recommendations/cinema-bourbaki.jpg",
    name: "Cinema Bourbaki",
    tagline: "Arthouse & Swiss films",
    address: "Löwenplatz 11, 6004 Luzern",
    website: "https://www.bourbakipanorama.ch",
    price_range: 2,
    description: "The Bourbaki cinema in Lucerne is a charming arthouse cinema in the historic Bourbaki Panorama. It shows carefully curated films – from current arthouse productions to classics – mostly in their original language. With comfortable seats, modern technology, and an intimate atmosphere, every visit to the cinema is a special experience. The inviting foyer with bar is the perfect place to linger before or after the show, making the Bourbaki a cultural meeting place for cineastes and curious minds alike.",
    bus_route: "Take bus no. 14 to Lucerne Wey, then walk for 4 minutes.",
    tags: ["rainy-day", "evening"],
  },
  {
    ...BASE,
    id: 34, slug: "glacier-garden", category: "culture", sort_order: 50,
    image_url: "/images/recommendations/glacier-garden.jpg",
    name: "Glacier Garden",
    tagline: "Mirror Maze & Ice Age history",
    address: "Denkmalstrasse 4a, 6006 Luzern",
    website: "https://www.gletschergarten.ch",
    phone: "+41 41 410 43 40",
    price_range: 2,
    description: "The Glacier Garden in Lucerne is a unique natural and cultural monument that combines impressive traces of the Ice Age with an exciting history. Visitors can discover glacier pots, fossils, and rock formations that are millions of years old, as well as interactive exhibitions on the history of the Earth. The historic Hall of Mirrors and the observation tower offer additional special experiences. With its mix of science, nature, and architecture, the Glacier Garden is a fascinating destination for young and old alike.",
    bus_route: "Take bus no. 14 to Lucerne Wey, walk past Bourbaki and continue on a side street until you reach the Lion Monument. The Glacier Garden is located there.",
    tags: ["family-friendly", "rainy-day"],
  },
  {
    ...BASE,
    id: 35, slug: "beach-bath-lido", category: "culture", sort_order: 60,
    image_url: "/images/recommendations/beach-bath-lido.jpg",
    name: "Beach Bath Lido",
    tagline: "Swimming · volleyball · paddleboarding",
    address: "Lidostrasse 6A, 6006 Luzern",
    website: "https://www.lido-luzern.ch",
    phone: "+41 41 370 38 06",
    price_range: 1,
    description: "The Lido beach in Lucerne is a summer hotspot right on Lake Lucerne. With its extensive sandy beach, large sunbathing lawn, and clear water, it is ideal for swimming, sunbathing, and relaxing. Sporty guests can enjoy beach volleyball courts, a diving tower, or stand-up paddleboarding, while children can splash around safely in the shallow waters near the shore. Refreshments and snacks are available. The Lido combines a vacation feeling with urban proximity – perfect for hot days.",
    bus_route: "Take bus no. 14 to Lucerne train station, then bus no. 6 or 8 to Verkehrshaus-Lido, then walk 7 minutes along the lake and past the Verkehrshaus.",
    tags: ["sunny-day", "lake", "family-friendly"],
  },
  {
    ...BASE,
    id: 36, slug: "lake-bath-lucerne", category: "culture", sort_order: 70,
    image_url: "/images/recommendations/lake-bath-lucerne.jpg",
    name: "Lake Bath Lucerne",
    tagline: "Historic Seebad since 1885 · wooden decks",
    address: "Nationalquai, 6006 Luzern",
    website: "https://www.seebadluzern.ch",
    price_range: 1,
    description: "The Seebad Luzern is a charming, historic bathing establishment directly on Lake Lucerne, which has been part of summer city life since 1885. On the wooden complex with two separate bathing areas for men and women and a shared swimming area, you can relax in the lake, sunbathe, and enjoy the view of Mount Pilatus and Mount Rigi. A bar and restaurant provide refreshments and light meals, while deck chairs and sun decks invite you to linger. A place with nostalgic flair and a holiday feeling in the heart of Lucerne.",
    bus_route: "Take bus no. 14 to the Luzern Wey stop, then walk 8 minutes along the lake.",
    tags: ["sunny-day", "lake"],
  },
  {
    ...BASE,
    id: 37, slug: "kkl-lucerne", category: "culture", sort_order: 80,
    image_url: "/images/recommendations/kkl-lucerne.jpg",
    name: "KKL Lucerne",
    tagline: "Classical music · art · theater",
    address: "Europaplatz 1, 6005 Luzern",
    website: "https://www.kkl-luzern.ch",
    phone: "+41 41 226 77 77",
    price_range: 3,
    description: "The KKL Luzern is an architectural masterpiece by Jean Nouvel and one of Switzerland's most important cultural centers. Located directly on Lake Lucerne, it impresses with its spectacular architecture and excellent acoustics. World-renowned festivals such as the Lucerne Festival, high-caliber concerts, exhibitions, and conferences take place here. The interplay of art, music, cuisine, and a unique location makes the KKL a cultural landmark and meeting place for guests from all over the world.",
    bus_route: "The KKL is right next to Lucerne train station. It is a large building with lots of windows, directly on the lake.",
    why_we_love_it: "Film with live music by the 21st Century Orchestra",
    tags: ["evening", "rainy-day"],
  },
  {
    ...BASE,
    id: 38, slug: "chapel-bridge", category: "culture", sort_order: 90,
    image_url: "/images/recommendations/chapel-bridge.jpg",
    name: "Chapel Bridge",
    tagline: "Lucerne's 14th-century covered bridge",
    address: "Altstadt, Luzern",
    description: "The Chapel Bridge is Lucerne's landmark and one of the oldest covered wooden bridges in Europe. Built in the 14th century, it connects the old town with the new town and impresses with historical triangular paintings depicting scenes from the city's history. Together with the striking water tower, it forms a picturesque ensemble that is one of the most photographed sights in Switzerland. A walk across the Chapel Bridge is a must for every visitor to Lucerne.",
    bus_route: "Take bus no. 14 to Lucerne train station, then look towards the old town. The bridge is impossible to miss.",
    tags: ["photo-spot"],
  },
  {
    ...BASE,
    id: 39, slug: "conservatory", category: "culture", sort_order: 100,
    image_url: "/images/recommendations/conservatory.jpg",
    name: "Conservatory",
    tagline: "Open views over the lake from the park — a local tip",
    address: "Dreilindenstrasse 93, 6006 Luzern",
    lat: 47.0631, lng: 8.3253,
    description: "Not in the old town — this is in the Neustadt, up the hill in the Dreilindenpark. A quiet park with old trees, open views over the lake, and mostly locals. The conservatory building sits in the middle of it. Good for a slow walk, a sit-down with a view, or catching a concert if something is on. Few tourists make it up here, which is part of the appeal.",
    bus_route: "Take bus no. 14 to Lucerne Conservatory, then walk up the stairs on the other side of the street.",
    why_we_love_it: "Bring a picnic and enjoy the breathtaking view. There is no restaurant at the conservatory.",
    tags: ["personal-favorites", "view", "hidden-gem", "photo-spot"],
  },
  {
    ...BASE,
    id: 40, slug: "lion-monument", category: "culture", sort_order: 110,
    image_url: "/images/recommendations/lion-monument.jpg",
    name: "Lion Monument",
    tagline: "Moving symbol of bravery",
    address: "Denkmalstrasse 4, 6002 Luzern",
    description: "The Lion Monument in Lucerne is one of Switzerland's most famous monuments and a moving symbol of bravery and loyalty. It commemorates the Swiss guards who fell in Paris during the French Revolution in 1792. The dying lion, carved into a rock face, impresses with its expressiveness and emotional depth. Surrounded by a peaceful park, the monument is a place of tranquility and reflection—and an important part of Lucerne's city history.",
    bus_route: "Take bus no. 14 to Lucerne Wey, walk past Bourbaki and continue on a side street until you reach the Lion Monument. The Glacier Garden is also located there.",
    tags: ["photo-spot"],
  },
  {
    ...BASE,
    id: 41, slug: "musegg-wall", category: "culture", sort_order: 120,
    image_url: "/images/recommendations/musegg-wall.jpg",
    name: "Musegg Wall",
    tagline: "Medieval city wall · 9 towers",
    address: "Denkmalstrasse 4, 6002 Luzern",
    description: "The Musegg Wall in Lucerne is a well-preserved section of the historic city fortifications dating back to the 14th century and is one of the city's landmarks. Nine striking towers dominate the skyline, some of which can be climbed to enjoy impressive views of the old town, Lake Lucerne, and the surrounding mountains. Open in spring and summer, the Musegg Wall invites you to take a walk through history and experience the authentic atmosphere of medieval Lucerne.",
    bus_route: "Take bus no. 14 to Pilatusplatz, then walk through the old town for 10 minutes, across Mühlenplatz, past the Karls Kraut restaurant. There you will find the first tower of the Musegg Wall.",
    why_we_love_it: "Aperitif at the Buurebeizli Hinter Musegg",
    tags: ["photo-spot", "view"],
  },

  // ── HIKE (Mountains & Viewpoints) ───────────────────────────────────────
  {
    ...BASE,
    id: 50, slug: "mount-pilatus", category: "hike", sort_order: 10,
    image_url: "/images/recommendations/mount-pilatus.jpg",
    name: "Mount Pilatus",
    tagline: "Lucerne's local mountain · gondola from Kriens · 2,132 m",
    address: "Schlossweg 1, 6010 Kriens",
    lat: 47.0262, lng: 8.2556,
    website: "https://www.pilatus.ch",
    phone: "+41 41 329 11 11",
    price_range: 4,
    description: "Pilatus is practically on the doorstep — the gondola base station is a few minutes from the apartment by bus. Take the gondola up from Kriens, walk one of the ridge trails, and come back down via the mountain railway to Alpnachstad (or the other way around). On a clear day the views over Lake Lucerne and the Alps are genuinely worth it. The summit area has a restaurant and hotel if you want to stay for sunset.",
    bus_route: "Take bus no. 21 from Kriens, Sternmatt (approx. 100 m from the apartment) to Kriens, Zentrum - Pilatus and walk to the valley station.",
    tags: ["personal-favorites", "view", "mountain", "photo-spot"],
  },
  {
    ...BASE,
    id: 51, slug: "mount-titlis", category: "hike", sort_order: 20,
    image_url: "/images/recommendations/mount-titlis.jpg",
    name: "Mount Titlis",
    tagline: "Glacier experience · 3,000 m altitude · Rotair cable car",
    address: "Engelberg",
    website: "https://www.titlis.ch",
    price_range: 4,
    description: "The Titlis near Engelberg is a spectacular destination and a year-round highlight in Central Switzerland. The rotating Rotair cable car takes you up to over 3,000 meters, where breathtaking views, eternal snow, and glacier experiences await. Visitors can cross the Cliff Walk – Europe's highest suspension bridge – hike on the glacier or simply enjoy the mountain scenery. In winter, the Titlis attracts visitors with its varied ski slopes, while in summer it offers hiking trails and adventure activities.",
    bus_route: "Take bus no. 14 to Lucerne train station, from where the IRLEX express train runs directly to Engelberg. In Engelberg, a footpath leads to the valley station in 10 minutes.",
    tags: ["view", "mountain", "photo-spot"],
  },
  {
    ...BASE,
    id: 52, slug: "mount-rigi", category: "hike", sort_order: 30,
    image_url: "/images/recommendations/mount-rigi.jpg",
    name: "Mount Rigi",
    tagline: "Queen of the Mountains · 360° panoramic view",
    address: "Vitznau",
    website: "https://www.rigi.ch",
    price_range: 3,
    description: "The Rigi, also known as the \"Queen of the Mountains,\" offers a 360-degree panorama of Lake Lucerne, Lake Zug, and the Alps. It is a popular destination all year round and can be easily reached by mountain railway or cable car. In summer, idyllic hiking trails and picnic spots invite you to linger, while in winter, snowshoe trails and sleigh rides beckon. The combination of nature, views, and accessibility makes the Rigi a classic among Swiss mountains.",
    bus_route: "Take the train from Lucerne to Arth-Goldau and from there take the train up to the Rigi. Or take the boat from Lucerne to Vitznau and ride up on the historic mountain railway.",
    tags: ["view", "mountain", "photo-spot"],
  },
  {
    ...BASE,
    id: 53, slug: "stanserhorn", category: "hike", sort_order: 40,
    image_url: "/images/recommendations/stanserhorn.jpg",
    name: "Stanserhorn",
    tagline: "Cabrio-Bahn — world's first open upper deck cable car",
    address: "Stans",
    website: "https://www.stanserhorn.ch",
    phone: "+41 41 618 80 40",
    price_range: 3,
    description: "The Stanserhorn in Nidwalden combines nature and technological history in a unique way. The journey begins with a nostalgic funicular railway and continues with the Cabrio Bahn – the world's first cable car with an open upper deck. At the top, visitors are greeted by breathtaking panoramic views of lakes and mountains, leisurely hiking trails, and the Stanserhorn restaurant serving regional specialties. The protected area around the summit is also home to rare plants and animals, making a visit here truly special.",
    bus_route: "Walk to Kriens, Mattenhof station. Then take the S4 train to Stans and walk through the town to the valley station.",
    tags: ["view", "mountain", "hidden-gem"],
  },
  {
    ...BASE,
    id: 54, slug: "klewendalp", category: "hike", sort_order: 50,
    image_url: "/images/recommendations/klewendalp.jpg",
    name: "Klewenalp",
    tagline: "Scenic walks · family-friendly · gondola",
    address: "Beckenried",
    website: "https://www.klewenalp.ch",
    phone: "+41 41 624 66 00",
    price_range: 3,
    description: "The Klewenalp above Beckenried is a family-friendly destination offering magnificent views of Lake Lucerne and the surrounding Alps. Accessible by gondola lift, it offers idyllic hiking trails, bike routes, and barbecue areas in summer, and a small, charming ski area with wide slopes in winter. Cozy mountain restaurants invite you to linger, while the relaxed atmosphere and wide range of leisure activities make Klewenalp a popular destination for those seeking relaxation and nature lovers.",
    bus_route: "Only accessible by car (large parking lot available at the valley station).",
    tags: ["family-friendly", "mountain"],
  },
  {
    ...BASE,
    id: 55, slug: "lakeview-biregg", category: "hike", sort_order: 60,
    image_url: "/images/recommendations/lakeview-biregg.jpg",
    name: "Lakeview Biregg",
    tagline: "On foot from the apartment — insider tip",
    address: "Auf Oberrüti 19, 6048 Horw",
    lat: 47.0281, lng: 8.2988,
    description: "Start in Nidfeld and walk leisurely towards the Allmend stadium until you reach the Waldegg Horw bus stop. This is where the idyllic Bireggwald forest begins. The trail leads through a beautiful mixed forest up to the Felmis district, which is picturesquely situated on the southwestern edge of the forest. Continuing along the edge of the forest above the neighborhood, you will reach the Seeblick Oberrüti viewpoint, which offers a magnificent view of Lake Lucerne, the Rigi, and the Bürgenstock. From there, the trail descends along the edge of the forest to the Tribschen neighborhood. Here, the lake shore and small bathing spots invite you to linger. The route is around 5–7 kilometers long. Return from Lucerne station with bus no. 14 back to Nidfeld.",
    bus_route: "Start at Nidfeld, return via Bus 14 from Lucerne station.",
    why_we_love_it: "Take a picnic with you",
    tags: ["personal-favorites", "hidden-gem", "view", "lake"],
  },
  {
    ...BASE,
    id: 56, slug: "ship-to-buergenstock", category: "hike", sort_order: 70,
    image_url: "/images/recommendations/ship-to-buergenstock.jpg",
    name: "Ship to Bürgenstock",
    tagline: "Boat trip · panoramic views · funicular",
    address: "Landungsbrücke 1, 6003 Luzern",
    website: "https://www.lakelucerne.ch",
    phone: "+41 41 367 67 67",
    price_range: 3,
    description: "A boat trip from Lucerne to Bürgenstock combines relaxed travel with spectacular views. From the Lucerne lake basin, you glide past picturesque shores and mountains to the Bürgenstock station. From there, the funicular railway takes you up to the famous Bürgenstock Resort with breathtaking views over Lake Lucerne. Whether you prefer a walk, the panoramic terrace, or the spectacular rock trail, this excursion is a highlight for nature lovers and connoisseurs alike.",
    bus_route: "Take bus no. 14 to Lucerne train station; the boat is at the pier in front of the station.",
    tags: ["view", "lake"],
  },
  {
    ...BASE,
    id: 57, slug: "ship-to-brunnen", category: "hike", sort_order: 80,
    image_url: "/images/recommendations/ship-to-brunnen.jpg",
    name: "Ship to Brunnen",
    tagline: "3-hour lake crossing · alpine scenery",
    address: "Landungsbrücke 1, 6003 Luzern",
    website: "https://www.lakelucerne.ch",
    phone: "+41 41 367 67 67",
    price_range: 3,
    description: "A boat trip from Lucerne to Brunnen is an experience that combines picture-postcard idylls with dramatic alpine scenery. The journey takes you across Lake Lucerne, past picturesque shores, charming villages, and steep rock faces. Along the way, you can enjoy views of Mount Rigi, Mount Pilatus, and the Bürgenstock. Depending on the boat—whether a nostalgic paddle steamer or a modern motorboat—you can enjoy the fresh lake air on deck or relax in the saloon with coffee and snacks. In Brunnen, visitors can enjoy a lakeside promenade with views of the Alps, cafés, and the legendary Schweizerhofplatz square.",
    bus_route: "Take bus no. 14 to Lucerne train station; the boat is at the pier in front of the station.",
    tags: ["lake", "view"],
  },

  // ── WALKS ──────────────────────────────────────────────────────────────
  {
    ...BASE,
    id: 101, slug: "bireggwald", category: "walks", sort_order: 20,
    image_url: "/images/recommendations/walk-02-bireggwald.jpg",
    name: "Bireggwald",
    tagline: "Mixed forest with a fitness loop and grill clearing",
    description: "Mixed forest between Kriens, Horw and the southern edge of Lucerne. Marked paths, free Vita Parcours fitness loop with 14 stations, picnic spots, a grill clearing with partial lake view. The 'Rigiblick' inside the forest is a single bench in a clearing — modest, not a panoramic terrace.",
    walk_time_min: 10,
    season: ["spring", "summer", "autumn", "winter"],
    tags: ["family-friendly"],
    why_we_love_it: "Wild garlic carpets the floor in April–May.",
  },
  {
    ...BASE,
    id: 102, slug: "himmelrich-loop", category: "walks", sort_order: 30,
    image_url: "/images/recommendations/walk-01-himmelrich.jpg",
    name: "Himmelrich Loop",
    tagline: "Farm tracks above Kriens with two honour-system farm shops",
    description: "A loop up the Schattenbergstrasse on the southern slope above Kriens, past a few working farms. Mostly tarmac and farm tracks; views over Kriens and the lake. Two honour-system farm shops on the route: Hof Niederberger (eggs, jam) and the Buholzer family at Gabeldingen (raw milk 1.30 CHF/litre, apple juice, eggs). Both take Twint or cash.",
    bus_route: "On foot from Nidfeldstrasse: cross Pilatusstrasse, then uphill via Schachenstrasse and Schattenbergstrasse. 15–20 min of gradual climbing to reach the open section.",
    walk_time_min: 15,
    season: ["spring", "summer", "autumn", "winter"],
    tags: [],
  },
  {
    ...BASE,
    id: 103, slug: "nationalquai-promenade", category: "walks", sort_order: 40,
    image_url: "/images/recommendations/walk-08-nationalquai.jpg",
    name: "Nationalquai Promenade",
    tagline: "Lucerne's main lakefront promenade",
    description: "Lucerne's main lakefront promenade, from the KKL concert hall to the Casino and Kurplatz. Flat, partly shaded, busy in good weather. Views toward Pilatus, Rigi and Bürgenstock.",
    bus_route: "Via Lucerne station (bus 14 from Kriens, Nidfeld, ~10 min). Promenade starts directly behind the KKL.",
    season: ["spring", "summer", "autumn", "winter"],
    tags: ["lake", "view", "family-friendly"],
  },
  {
    ...BASE,
    id: 104, slug: "tribschen-peninsula", category: "walks", sort_order: 50,
    image_url: "/images/recommendations/walk-10-tribschen.jpg",
    name: "Tribschen Peninsula",
    tagline: "Wagner's lakeside home — quiet alternative to the busy promenade",
    description: "Wooded peninsula south of the train station where Richard Wagner lived in the 1860s. Lakeside park is free and open; the museum in his former house has period rooms and an audio guide. Quiet alternative to the busy city promenade. Museum closed Mondays; otherwise 11:00–17:00.",
    bus_route: "Via Lucerne station, then a short bus ride toward Wartegg, then 5 min walk down to the lake. Check SBB Mobile for the current line.",
    website: "https://www.richard-wagner-museum.ch",
    season: ["spring", "summer", "autumn", "winter"],
    tags: ["lake", "culture"],
  },
  {
    ...BASE,
    id: 105, slug: "krienseregg-gondola", category: "walks", sort_order: 60,
    image_url: "/images/recommendations/walk-13-krienseregg.jpg",
    name: "Krienseregg (Pilatus Mid-Station)",
    tagline: "The least-effort way into the mountains from the door",
    description: "Mid-station of the Pilatus gondola from Kriens. Wooded plateau with the Pilu Land children's playground, fire pits, self-service restaurant, gentle paths through pasture. The least-effort way into the mountains and the most kid-friendly option from the door.",
    bus_route: "Pilatus gondola from Kriens. The valley station is at 'Kriens, Pilatus-Bahnen' — short bus ride or walk from the apartment (longer than you might think). Ride to Krienseregg about 10 min, 2 stops.",
    website: "https://www.pilatus.ch/en",
    season: ["spring", "summer", "autumn", "winter"],
    tags: ["mountain", "family-friendly"],
    why_we_love_it: "Bring wood for the grills on Sundays — sometimes the wood box is empty.",
  },
  {
    ...BASE,
    id: 106, slug: "sonnenberg-loop", category: "walks", sort_order: 70,
    image_url: "/images/recommendations/walk-14-sonnenberg.jpg",
    name: "Sonnenberg & Chrüzhöchi",
    tagline: "Easy ridge walk above Kriens via funicular",
    description: "Easy circular route on the Sonnenberg ridge above Kriens. Views across Lucerne and the lake. Picnic spots, small hotel-restaurant. With children, the ComicTrail riddle path adds a game along the way.",
    bus_route: "Sonnenbergbahn (funicular) — valley station at 'Kriens (Sonnenbergbahn)'. Allow some walking time from the apartment, or check the SBB app for local transport. Ride to the top about 5 min.",
    website: "https://www.sonnenbergbahn.ch",
    season: ["spring", "summer", "autumn", "winter"],
    tags: ["view", "mountain", "family-friendly"],
  },
  {
    ...BASE,
    id: 107, slug: "buergenstock-felsenweg", category: "walks", sort_order: 80,
    image_url: "/images/recommendations/walk-16-felsenweg.jpg",
    name: "Bürgenstock: Felsenweg & Hammetschwand",
    tagline: "Cliff path ending at Europe's tallest outdoor lift",
    description: "Path cut into the cliff face along the northern flank of the Bürgenstock, broad and well-secured. Ends at the Hammetschwand outdoor elevator (tallest outdoor lift in Europe, 153 m, built 1905). About 35 min one way. The plateau at the resort has a separate level promenade with flower beds and viewpoints — easy to add on. The resort cafés are pricey.",
    bus_route: "Via Lucerne station, boat to Kehrsiten-Bürgenstock, then Bürgenstock funicular up to the resort plateau.",
    website: "https://www.lakelucerne.ch",
    season: ["spring", "summer", "autumn"],
    tags: ["view", "lake"],
    why_we_love_it: "Hammetschwand lift charges ~15 CHF return, separate from the funicular. Walk to it is free. Path best May–October — check current status before going.",
  },
  {
    ...BASE,
    id: 108, slug: "rigi-kaltbad-panorama", category: "walks", sort_order: 90,
    image_url: "/images/recommendations/walk-17-rigi-kaltbad.jpg",
    name: "Rigi Kaltbad Panorama Loop",
    tagline: "Wide gravel paths above the lake — often above the fog",
    description: "Wide gravel paths around the Rigi Kaltbad mid-station, with views across the lake. Mostly level, suitable for all abilities and prams. The mid-station has a modern spa (Mineralbad & Spa Rigi Kaltbad, designed by Mario Botta) — book ahead if interested. Often above the fog in autumn and winter. Check weather before going.",
    bus_route: "Via Lucerne station, boat to Vitznau, then mountain railway up to Rigi Kaltbad.",
    website: "https://www.rigi.ch/en",
    season: ["spring", "summer", "autumn", "winter"],
    tags: ["view", "mountain", "family-friendly"],
  },

  // ── ADDITIONAL HIKES ───────────────────────────────────────────────────
  {
    ...BASE,
    id: 58, slug: "four-lakes-hike", category: "hike", sort_order: 85,
    image_url: "/images/recommendations/hike-01-four-lakes.jpg",
    name: "Four Lakes Hike",
    tagline: "Engelberg to Melchsee-Frutt over the Jochpass",
    description: "Trübsee → Engstlensee → Tannensee → Melchsee. Four alpine lakes connected by a marked path that crosses the Jochpass (2,207 m). Technically easy walking on broad tracks, but a long day with the Jochpass climb. Restaurant at each lake. For experienced walkers with an early start — check last cable cars before leaving.",
    bus_route: "Via Lucerne station, train to Engelberg (about 45 min), Titlis cableway to Trübsee. Return: Stöckalp gondola, then PostBus to Sarnen, train to Lucerne, then back via Lucerne station.",
    website: "https://www.titlis.ch/en",
    season: ["summer", "autumn"],
    tags: ["mountain", "view"],
    why_we_love_it: "Two shortcuts: Jochpass chairlift up from Trübsee, and Stöckalp gondola at the end. Even with both, the day stays substantial.",
  },
  {
    ...BASE,
    id: 59, slug: "stoos", category: "hike", sort_order: 87,
    image_url: "/images/recommendations/hike-02-stoos-ridge.jpg",
    name: "Stoos",
    tagline: "Ridge hike or village walk · world's steepest funicular",
    description: "## Stoos Ridge — Klingenstock to Fronalpstock\nRidge between two summits above Brunnen. The path follows the spine with views down both sides — Vierwaldstättersee on one, the Mythen and Muotatal on the other. Some stairs and steeper bits; not for those unsteady on rocky steps.\n\n## Stoos Village Loop\nEasier alternative. Stoos is a car-free village on a terrace 1,300 m above the lake. A marked loop trail follows the rim with constant views. The world's steepest funicular (110% maximum gradient) takes you up — an attraction in itself, particularly with children.",
    bus_route: "Via Lucerne station, train to Schwyz (about 45 min), bus to Schwyz-Stoosbahn, funicular up to Stoos village.",
    website: "https://www.stoos.ch",
    season: ["summer", "autumn"],
    tags: ["mountain", "view", "family-friendly"],
    why_we_love_it: "Ridge: Single combined ticket covers funicular, Klingenstock chairlift up, and Fronalpstock chairlift down. Go midweek or early.\n\nVillage loop: Good option with children — the funicular ride alone is worth it.",
  },
  {
    ...BASE,
    id: 61, slug: "pilatus-climb-alpnachstad", category: "hike", sort_order: 15,
    image_url: "/images/recommendations/hike-04-pilatus-climb.jpg",
    name: "Pilatus: Walk Up from Alpnachstad",
    tagline: "Forest, alpine meadow, rocky summit — walk up, ride down",
    description: "For guests who want to walk up and ride down. The trail from Alpnachstad climbs through forest, then alpine meadow, then rocky upper slopes to Pilatus Kulm. Long but technically straightforward — no exposure. An honour-system cheese fridge sits at Aemsigen, roughly halfway up. A proper uphill hike, not a casual walk. Start early and check descent options.",
    bus_route: "Via Lucerne station, train to Alpnachstad (about 20 min).",
    website: "https://www.pilatus.ch/en",
    season: ["spring", "summer", "autumn"],
    tags: ["mountain", "view"],
    why_we_love_it: "Buy a one-way mountain railway ticket at the top for the descent. For half the distance, take the mountain railway up to Aemsigen and walk only the upper section. Sturdy hiking boots are essential — the upper section is rocky and this is a demanding hike, not a casual walk.",
  },

  // ── BOATS ──────────────────────────────────────────────────────────────
  {
    ...BASE,
    id: 70, slug: "paddle-steamer-cruise", category: "boats", sort_order: 10,
    image_url: "/images/recommendations/boat-03-paddle.jpg",
    name: "Paddle Steamer Day Cruise",
    tagline: "Five Belle Époque steamers still in regular service",
    description: "Lake Lucerne keeps five working Belle Époque paddle steamers in regular service: Uri, Unterwalden, Schiller, Gallia, Stadt Luzern. Several offer dining on board, and the engineering is on display through glass panels in the engine room. You can ride the full lake or just the segment that fits your day — Weggis (55 min one way) for lunch and back, or Vitznau (1 hr) to connect with the Rigi.",
    bus_route: "Via Lucerne station (bus 14 from Kriens, Nidfeld, ~10 min), then 3 min walk to Pier 1.",
    website: "https://www.lakelucerne.ch",
    season: ["spring", "summer", "autumn"],
    tags: ["lake", "family-friendly"],
    why_we_love_it: "Upper-deck first class is worth the extra in good weather.",
  },
  {
    ...BASE,
    id: 71, slug: "golden-round-trip", category: "boats", sort_order: 20,
    image_url: "/images/recommendations/boat-06-golden-round.jpg",
    name: "Golden Round Trip",
    tagline: "Boat · mountain railway · gondola — one ticket, full day",
    description: "Boat to Alpnachstad, then the mountain railway up Pilatus (steepest in the world, max gradient 48%), gondola descent via Fräkmüntegg and Krienseregg back to Kriens. One combination ticket covers all four legs. The whole day is a long one, but the variety of transport is the appeal.",
    bus_route: "Via Lucerne station (bus 14 from Kriens, Nidfeld, ~10 min), 3 min to Pier 1. End of trip arrives back at Kriens, Pilatus-Bahnen — short bus ride or walk from the apartment.",
    website: "https://www.pilatus.ch/en",
    season: ["spring", "summer", "autumn"],
    tags: ["mountain", "lake", "family-friendly"],
  },
  {
    ...BASE,
    id: 72, slug: "grand-tour-flüelen", category: "boats", sort_order: 30,
    image_url: "/images/recommendations/boat-01-grand-tour.jpg",
    name: "Grand Tour: Lucerne to Flüelen",
    tagline: "The full crossing — cliffs, villages, the dramatic Urnersee",
    description: "The full Vierwaldstättersee crossing, calling at Weggis, Vitznau, Beckenried, Brunnen, Rütli, Sisikon and Flüelen. The southern arm (the Urnersee) has steeper cliffs and a different character than the northern half. Return by the same route, or by train from Flüelen via Arth-Goldau in about 1 hour. Snack bar and seated restaurant on board.",
    bus_route: "Via Lucerne station (bus 14 from Kriens, Nidfeld, ~10 min), 3 min to Pier 1.",
    website: "https://www.lakelucerne.ch",
    season: ["spring", "summer", "autumn"],
    tags: ["lake", "view"],
  },
  {
    ...BASE,
    id: 73, slug: "sunset-cruise", category: "boats", sort_order: 40,
    image_url: "/images/recommendations/boat-02-sunset.jpg",
    name: "Sunset Cruise",
    tagline: "Evening on the water — the Bürgenstock cliffs turn warm",
    description: "Evening departures in summer, usually on a paddle steamer with an on-board restaurant. The Bürgenstock cliffs turn warm in the low light. Often combined with dinner on board.",
    bus_route: "Via Lucerne station (bus 14 from Kriens, Nidfeld, ~10 min), 3 min to Pier 1.",
    website: "https://www.lakelucerne.ch",
    season: ["spring", "summer"],
    tags: ["lake", "sunset", "evening"],
  },
  {
    ...BASE,
    id: 74, slug: "sunday-brunch-cruise", category: "boats", sort_order: 50,
    image_url: "/images/recommendations/boat-08-brunch.jpg",
    name: "Sunday Brunch Cruise",
    tagline: "Buffet breakfast on the lake — departure 09:30",
    description: "Sunday-morning brunch cruise, on either a modern motor vessel or a paddle steamer depending on date. Buffet on board. Works well with children — the pace is slow and breakfast keeps everyone happy.",
    bus_route: "Via Lucerne station (bus 14 from Kriens, Nidfeld, ~10 min), 3 min to Pier 1.",
    website: "https://www.lakelucerne.ch",
    season: ["spring", "summer", "autumn"],
    tags: ["lake", "family-friendly", "morning"],
    why_we_love_it: "Pre-booking essential. Departure usually 09:30, returning by lunchtime.",
  },

  // ── CYCLING ────────────────────────────────────────────────────────────
  {
    ...BASE,
    id: 81, slug: "cycling-horwerhalbinsel", category: "bike", sort_order: 10,
    image_url: "/images/recommendations/cycling-01-horwerhalbinsel.jpg",
    name: "Horwerhalbinsel Loop",
    tagline: "A local peninsula circuit — shoreline, vineyard slopes, swim stops",
    description: "A small peninsula reaching into the lake south of the apartment. The loop follows the shoreline almost entirely — quiet residential lanes, lakeside path, vineyard slopes above. Stops along the way: Winkel Horw with the Sea Lion sculpture, Seebad Horw for a swim, Kastanienbaum Plätzli at the southern tip, the small harbour at Hermitage. A real local circuit close to the door.",
    bus_route: "Directly from Nidfeldstrasse — head south via Schachenstrasse and Kuonimattstrasse to Horw, then follow the lakeshore signs around the peninsula.",
    season: ["spring", "summer", "autumn"],
    tags: ["lake", "family-friendly"],
  },
  {
    ...BASE,
    id: 85, slug: "cycling-velohighway", category: "bike", sort_order: 15,
    image_url: "/images/recommendations/cycling-02-velohighway.jpg",
    name: "Velohighway Kriens → Luzern",
    tagline: "Dedicated cycle path from the door to the old town — flat, mostly traffic-free",
    description: "Dedicated regional cycle route from Kriens into Lucerne city, mostly separated from traffic. The fastest and safest way to reach the lakeshore, the KKL, and the old town by bike. Natural stop at Ufschötti for a coffee or a swim. Return the same way, or take the bike on bus 14 (limited capacity — check signage).",
    bus_route: "From Nidfeldstrasse, join the signed Velohighway at Schachenstrasse and follow it north toward Luzern.",
    website: "https://www.publibike.ch",
    season: ["spring", "summer", "autumn"],
    tags: ["lake"],
  },
  {
    ...BASE,
    id: 80, slug: "cycling-meggen-meggenhorn", category: "bike", sort_order: 20,
    image_url: "/images/recommendations/cycling-03-meggen.jpg",
    name: "Lakeshore to Meggen & Meggenhorn",
    tagline: "Easy lakeshore ride to a neo-Gothic castle and Strandbad",
    description: "Lucerne lakeshore east toward Meggen, on the signed Veloweg along the water. Mostly flat, partly separated from traffic. Strandbad Meggen for a swim, Meggenhorn castle gardens at the end (Sundays only for the castle itself). Return by the same route, or by boat from Meggen Gottlieben (bikes carried for a small fee).",
    bus_route: "Via Lucerne station (bus 14 from Kriens, Nidfeld, ~10 min). Rent a Bike or Publibike station at the station forecourt; route starts behind the KKL.",
    website: "https://www.rentabike.ch/en/luzern",
    season: ["spring", "summer", "autumn"],
    tags: ["lake", "family-friendly"],
  },
  {
    ...BASE,
    id: 82, slug: "cycling-reuss-valley", category: "bike", sort_order: 30,
    image_url: "/images/recommendations/cycling-04-reuss.jpg",
    name: "Reuss Valley Toward Emmen",
    tagline: "Flat river path, shaded and local — less busy than the lakeshore",
    description: "From the old town along the Reuss river east through quiet riverside paths toward Emmen and Rathausen. Mostly on a dedicated cycle path along the water, shaded in summer, less busy than the lakeshore. Return the same way, or by S-Bahn from Emmen (bikes allowed).",
    bus_route: "Via Lucerne station (bus 14 from Kriens, Nidfeld, ~10 min), then start at the Reuss embankment behind the old town.",
    season: ["spring", "summer", "autumn"],
    tags: [],
  },
  {
    ...BASE,
    id: 83, slug: "cycling-sempachersee", category: "bike", sort_order: 40,
    image_url: "/images/recommendations/cycling-05-sempach.jpg",
    name: "Sempachersee Loop",
    tagline: "A quieter lake north-west of Lucerne — open countryside, less tourism",
    description: "Complete loop around the Sempachersee, a quieter lake north-west of Lucerne. Mostly flat, on dedicated paths and quiet farm roads. Sempach old town and the Vogelwarte ornithology centre as natural stops. Different in character to Lake Lucerne — more open countryside, less tourism.",
    bus_route: "Via Lucerne station (bus 14 from Kriens, Nidfeld, ~10 min), then S-Bahn to Sempach-Neuenkirch with bike (usually S1 or RE24, about 15–17 min). Loop starts at the lake.",
    website: "https://schweizmobil.ch",
    season: ["spring", "summer", "autumn"],
    tags: ["family-friendly"],
  },

  // ── SWIMMING ───────────────────────────────────────────────────────────
  {
    ...BASE,
    id: 90, slug: "lido-luzern", category: "swim", sort_order: 10,
    image_url: "/images/recommendations/swim-01-lido.jpg",
    name: "Lido Luzern",
    tagline: "Sandy beach, heated pool, lake access — the main summer complex",
    description: "Pay-to-enter complex on the Lucerne lakeshore: sandy beach, lake access with steps, heated outdoor pool, restaurant, lockers. Family-oriented, can get busy on hot weekends. The Ufschötti free lawn is next door for a quieter or budget option.",
    bus_route: "Via Lucerne station (bus 14 from Kriens, Nidfeld, ~10 min), then bus 6 or 8 to 'Verkehrshaus / Lido' (~10 min). Or 25 min walk along the lakeshore.",
    website: "https://www.lido-luzern.ch",
    price_range: 1,
    season: ["summer"],
    tags: ["lake", "sunny-day", "family-friendly"],
  },
  {
    ...BASE,
    id: 91, slug: "ufschoetti", category: "swim", sort_order: 20,
    image_url: "/images/recommendations/swim-02-ufschoetti.jpg",
    name: "Ufschötti",
    tagline: "Free public lakeshore lawn — the classic warm-evening city swim",
    description: "Wide free public lawn on the city lakeshore. Busy on warm evenings — locals after work, students, families. Small kiosk for ice cream and drinks. Lake access via steps and stones; gradual entry.",
    bus_route: "Via Lucerne station (bus 14 from Kriens, Nidfeld, ~10 min), then 10–15 min walk south-east toward Alpenquai. Or bus 6, 7 or 8 to Werkhofstrasse, 5 min walk.",
    season: ["summer"],
    tags: ["lake", "sunny-day", "budget", "evening"],
    why_we_love_it: "Usually empties by sundown — the earlier evening hours are the nicest.",
  },
  {
    ...BASE,
    id: 93, slug: "seebad-horw", category: "swim", sort_order: 40,
    image_url: "/images/recommendations/swim-04-horw.jpg",
    name: "Seebad Horw",
    tagline: "Pilatus views, low-key — reachable by bike from the apartment",
    description: "Small paid public bath on the southern lake at Horw, with the Pilatus in the background and the Sea Lion sculpture nearby. Quieter than the city baths. Mix of locals and weekend visitors. Reachable by bike from the apartment (about 20 min).",
    bus_route: "Bus from Kriens toward Horw, Seefeld — check SBB Mobile for the current route. Or directly by bike from the apartment (about 20 min).",
    bike_time_min: 20,
    website: "https://www.horw.ch",
    price_range: 1,
    season: ["summer"],
    tags: ["lake", "sunny-day"],
  },
  {
    ...BASE,
    id: 95, slug: "wartegg-tribschen", category: "swim", sort_order: 55,
    image_url: "/images/recommendations/swim-06-wartegg.jpg",
    name: "Wartegg / Tribschen Lakeshore",
    tagline: "Quiet local spot near the Wagner peninsula — no crowds",
    description: "Small public lakeshore stretch on the Tribschen peninsula, with a few flat lawn spots and stone steps into the water. Quieter and more local than Ufschötti — used mostly by people from the neighbourhood. Combine with a walk around the Wagner park.",
    bus_route: "Via Lucerne station (bus 14 from Kriens, Nidfeld, ~10 min), then bus 6 or 7 toward Wartegg, then 5 min walk down to the lake.",
    season: ["summer"],
    tags: ["lake", "sunny-day", "budget", "evening"],
  },
  {
    ...BASE,
    id: 96, slug: "reussschwimmen", category: "swim", sort_order: 60,
    image_url: "/images/recommendations/swim-07-reuss.jpg",
    name: "Reussschwimmen",
    tagline: "Drift 1.4 km down the Reuss through the old town — a local summer ritual",
    description: "Enter the Reuss at St. Karli, drift roughly 1,400 m downstream past the old town, and climb out at Xylophonweg / Alte Fähre. The Buvette Nordpol on the Reusszopf is the natural spot for a drink afterwards — but is not an exit point; the current pulls strongly toward Emmen here. The City of Lucerne and SLRG publish a Reusskarte with marked entries, exits and rescue stations.",
    bus_route: "Via Lucerne station (bus 14 from Kriens, Nidfeld, ~10 min), then 15 min walk through the old town to the St. Karli entry steps on the right bank.",
    website: "https://www.stadtluzern.ch/dienstleistungeninformation/26092",
    season: ["summer"],
    tags: ["lake", "hidden-gem", "morning"],
    why_we_love_it: "STRONG SWIMMERS ONLY — at own risk · current is real and unpredictable · life vest or wetsuit essential, not optional · never alone, never with children · Wickelfisch dry bag for keys and phone · do not enter if water is high, after storms, or murky · exit at Alte Fähre — the Reusszopf is NOT an exit point",
  },

  // ── CULTURE ADDITIONS ──────────────────────────────────────────────────
  {
    ...BASE,
    id: 42, slug: "verkehrshaus", category: "culture", sort_order: 115,
    image_url: "/images/recommendations/rainy-01-verkehrshaus.jpg",
    name: "Verkehrshaus Luzern",
    tagline: "Switzerland's most-visited museum — rail, air, navigation and space",
    description: "Switzerland's most-visited museum, covering rail, road, aviation, navigation and space. Surprisingly well designed and enjoyable even for adults without children. Several halls with full-sized vehicles, a planetarium, an IMAX cinema, and the Hans Erni art museum on the same campus.",
    address: "Lidostrasse 5, 6006 Luzern",
    bus_route: "Via Lucerne station (bus 14 from Kriens, Nidfeld, ~10 min), then bus 6 or 8 to 'Verkehrshaus' (~10 min). In summer also reachable by boat from the central piers.",
    website: "https://www.verkehrshaus.ch/en",
    price_range: 3,
    season: ["spring", "summer", "autumn", "winter"],
    tags: ["family-friendly", "rainy-day"],
  },
  {
    ...BASE,
    id: 43, slug: "sammlung-rosengart", category: "culture", sort_order: 125,
    image_url: "/images/recommendations/rainy-02-rosengart.jpg",
    name: "Sammlung Rosengart",
    tagline: "Picasso, Klee, Cézanne — a calm, well-edited private collection",
    description: "Small, well-edited private collection with works by Picasso, Klee, Cézanne, Monet, Chagall, Matisse and Miró. Calm, never overwhelming, walkable in under two hours. Many international guests don't know it — quieter than the Kunstmuseum.",
    address: "Pilatusstrasse 10, 6003 Luzern",
    bus_route: "Via Lucerne station (bus 14 from Kriens, Nidfeld, ~10 min). Museum is across the square from the station, 2 min walk.",
    website: "https://www.rosengart.ch",
    price_range: 2,
    season: ["spring", "summer", "autumn", "winter"],
    tags: ["rainy-day"],
  },
  {
    ...BASE,
    id: 44, slug: "neubad-luzern", category: "culture", sort_order: 135,
    image_url: "/images/recommendations/rainy-03-neubad.jpg",
    name: "Neubad Luzern",
    tagline: "Former indoor pool turned café and cultural space",
    description: "Former indoor swimming pool turned into a café, co-working space and cultural venue. The empty pool basin is now a deckchair area. Younger crowd than the old town. Bar, occasional concerts and exhibitions.",
    bus_route: "Via Lucerne station (bus 14 from Kriens, Nidfeld, ~10 min), then 15 min walk via the old town. Or take a city bus to Bundesplatz — check SBB Mobile.",
    website: "https://neubad.org",
    season: ["spring", "summer", "autumn", "winter"],
    tags: ["rainy-day"],
  },
  {
    ...BASE,
    id: 45, slug: "lilu-light-festival", category: "culture", sort_order: 145,
    image_url: "/images/recommendations/rainy-06-lilu.jpg",
    name: "Lilu Light Festival",
    tagline: "Free outdoor light installations across the old town — mid-January",
    description: "Two weeks in mid-January, Lucerne becomes a free outdoor light installation — projections on the old town facades, the KKL, the Jesuitenkirche, several bridges. A 90-minute walking route. Evenings only; busiest on Friday and Saturday. Goes well even in light rain.",
    bus_route: "Via Lucerne station (bus 14 from Kriens, Nidfeld, ~10 min). Trail starts in the old town.",
    website: "https://www.lilulucerne.ch",
    season: ["winter"],
    tags: ["evening"],
  },

  // ── SHOPPING & ESSENTIALS ──────────────────────────────────────────────
  {
    ...BASE,
    id: 200, slug: "migrolino-nidfeld", category: "essentials", sort_order: 10,
    image_url: "/images/recommendations/practical-01-migros.jpg",
    name: "migrolino Nidfeld",
    tagline: "Closest shop — long hours including Sundays",
    description: "Smallest and closest option for drinks, snacks, basic groceries, coffee, and breakfast items. Opens much longer than the supermarkets — useful for late arrivals, Sunday mornings, and forgotten essentials.",
    address: "Nidfeldstrasse 10, Kriens",
    walk_time_min: 5,
    lat: 47.0395, lng: 8.2818,
    season: ["spring", "summer", "autumn", "winter"],
    tags: ["budget", "walk-in"],
    why_we_love_it: "Mon–Fri 05:30–22:00, Sat–Sun 06:00–22:00.",
  },
  {
    ...BASE,
    id: 201, slug: "migros-mattenhof", category: "essentials", sort_order: 20,
    image_url: "/images/recommendations/essentials-migros-produce.jpg",
    name: "Migros Mattenhof",
    tagline: "Nearest option for full grocery shopping",
    description: "Full grocery shopping — fresh produce, dairy, household basics. Migros sells no alcohol; ALDI or Coop Pronto for that. The Mattenhof complex also has Bäckerei Hug (open Sundays) and Medbase pharmacy.",
    address: "Am Mattenhof 2, Kriens",
    walk_time_min: 10,
    lat: 47.0367, lng: 8.2832,
    season: ["spring", "summer", "autumn", "winter"],
    tags: ["family-friendly"],
    why_we_love_it: "Mon–Sat, closed Sunday. Always check current hours on site, especially around public holidays.",
  },
  {
    ...BASE,
    id: 202, slug: "pilatusmarkt", category: "essentials", sort_order: 30,
    image_url: "/images/recommendations/essentials-pilatusmarkt.jpg",
    name: "Pilatusmarkt",
    tagline: "Larger shopping centre with Coop, Jumbo and pharmacy — paid parking",
    description: "Good for larger shopping. Includes Coop supermarket, Coop Vitality pharmacy, Jumbo home & DIY, Confiseur Bachmann and other shops. Parking is paid. ALDI is nearby on the same street (Ringstrasse 27) but a separate building.",
    address: "Ringstrasse 19, Kriens",
    bus_route: "Bus from Kriens, Nidfeld — check SBB Mobile for the current line. About 45 min on foot — most guests take the bus.",
    walk_time_min: 45,
    lat: 47.0488, lng: 8.2933,
    season: ["spring", "summer", "autumn", "winter"],
    tags: ["family-friendly", "budget"],
    why_we_love_it: "Mon, Tue, Thu 09:00–18:30 · Wed, Fri 09:00–21:00 · Sat 08:00–16:00 · closed Sunday.",
  },
  {
    ...BASE,
    id: 203, slug: "bakeries", category: "essentials", sort_order: 40,
    image_url: "/images/recommendations/practical-03-bakery.jpg",
    name: "Bakeries — Hug & Heini",
    tagline: "Fresh bread and regional pastries, open from 06:00",
    description: "Two reliable local bakeries within 10 min walk. Bäckerei Hug at Mattenhof (Am Mattenhof 6) for fresh bread and pastries — open daily including Sundays. Konditorei Heini at Pilatusplatz for Nussgipfel and Luzerner Lebkuchen. The Luzerner Chügelipastete (puff-pastry pie) is a regional speciality worth trying.",
    walk_time_min: 10,
    lat: 47.0426, lng: 8.2848,
    season: ["spring", "summer", "autumn", "winter"],
    tags: ["morning", "walk-in"],
    why_we_love_it: "Bäckerei Hug: Mon–Fri 06:00–19:00, Sat–Sun 07:00–17:00 — one of the few options open on Sundays.",
  },
  {
    ...BASE,
    id: 204, slug: "pharmacy", category: "essentials", sort_order: 50,
    image_url: "/images/recommendations/practical-04-pharmacy.jpg",
    name: "Pharmacy (Apotheke)",
    tagline: "English-speaking staff at Mattenhof and Pilatusmarkt",
    description: "Medbase Apotheke at the Mattenhof complex (Am Mattenhof 4) is the closest pharmacy. Coop Vitality at Pilatusmarkt is further away. For Sunday or after-hours needs, the Bahnhof-Apotheke at Lucerne train station has extended hours and is open daily.",
    address: "Am Mattenhof 4, Kriens",
    walk_time_min: 10,
    lat: 47.0367, lng: 8.2842,
    season: ["spring", "summer", "autumn", "winter"],
    tags: [],
    why_we_love_it: "Medbase: Mon–Fri 08:00–18:30, Sat 08:00–16:00, closed Sunday. Bahnhof-Apotheke (Lucerne station) open daily — useful on Sundays and public holidays.",
  },
  {
    ...BASE,
    id: 205, slug: "sunday-shops", category: "essentials", sort_order: 60,
    image_url: "/images/recommendations/practical-02-sunday.jpg",
    name: "Sunday-Open Shops",
    tagline: "Swiss retail closes Sundays — here's what stays open",
    description: "Swiss retail otherwise closes Sundays. Coop Pronto and Migros at Lucerne train station open daily until 22:00 — full small supermarkets. Useful for arrivals or anything forgotten. migrolino Nidfeld (5 min walk from the apartment) is the closest option from the door.",
    bus_route: "Bus 14 from Kriens, Nidfeld to Lucerne station (~10 min). Shops inside the station.",
    lat: 47.0506, lng: 8.3094,
    season: ["spring", "summer", "autumn", "winter"],
    tags: ["walk-in"],
    why_we_love_it: "Daily including Sundays and public holidays.",
  },
  {
    ...BASE,
    id: 206, slug: "takeaway-nearby", category: "essentials", sort_order: 70,
    image_url: "/images/recommendations/practical-05-takeaway.jpg",
    name: "Easy Dinner at the Mattenhof",
    tagline: "Nooch Asian Kitchen · The Jack's House — 10 min walk",
    description: "A few reliable restaurants directly at the Mattenhof — the closest options for an easy first evening. Nooch Asian Kitchen for sushi, ramen and Asian dishes (open daily, late hours). The Jack's House for Balkan food (closed Mondays). Both have English menus. Phone ahead on weekends.",
    walk_time_min: 10,
    lat: 47.0444, lng: 8.2858,
    season: ["spring", "summer", "autumn", "winter"],
    tags: ["walk-in"],
    why_we_love_it: "Good option on the first evening after arrival, or when the supermarkets are shut.",
  },
];

export function getByCategory(category: string): Recommendation[] {
  return RECOMMENDATIONS.filter((r) => r.category === category && r.published)
    .sort((a, b) => a.sort_order - b.sort_order);
}

export function getBySlug(category: string, slug: string): Recommendation | undefined {
  return RECOMMENDATIONS.find((r) => r.category === category && r.slug === slug);
}

export function countByCategory(category: string): number {
  return RECOMMENDATIONS.filter((r) => r.category === category && r.published).length;
}
