import type { Recommendation } from "@/types/recommendation";

const BASE: Omit<Recommendation, "id" | "slug" | "category" | "name" | "tagline" | "sort_order"> = {
  description: null,
  why_we_love_it: null,
  address: null,
  lat: null,
  lng: null,
  website: null,
  phone: null,
  opening_hours: null,
  price_range: null,
  walk_time_min: null,
  bike_time_min: null,
  bus_route: null,
  season: [],
  tags: [],
  image_url: null,
  image_credit: null,
  source_url: null,
  google_place_id: null,
  image_reference: null,
  image_attribution: null,
  published: true,
  created_at: "",
  updated_at: "",
};

export const RECOMMENDATIONS: Recommendation[] = [
  // ── EAT ────────────────────────────────────────────────────────────────
  {
    ...BASE,
    id: 1, slug: "two-hands", category: "eat", sort_order: 10,
    name: "Two Hands",
    tagline: "Creative cosmopolitan cuisine",
    address: "Waldstätterstrasse 6, 6003 Luzern",
    bus_route: "Bus 14 → Moosmatt, 4 min walk",
    why_we_love_it: "Chai tea & homemade pancakes",
    tags: ["personal-favorites"],
  },
  {
    ...BASE,
    id: 2, slug: "melissas-kitchen", category: "eat", sort_order: 20,
    name: "Melissa's Kitchen",
    tagline: "Homemade, fresh, organic",
    address: "Hirschengraben 19, 6003 Luzern",
    bus_route: "Bus 14 → Pilatusplatz, 5 min walk",
    why_we_love_it: "Big brunch buffet on Sundays & holidays",
  },
  {
    ...BASE,
    id: 3, slug: "karls-kraut", category: "eat", sort_order: 30,
    name: "Karls Kraut",
    tagline: "Vegan & plant-based",
    address: "St. Karliquai 7, 6004 Luzern",
    bus_route: "Bus 14 → Pilatusplatz, 10 min walk",
    why_we_love_it: "Brunch every 2nd & 4th Sunday",
    tags: ["vegetarian"],
  },
  {
    ...BASE,
    id: 4, slug: "pastarazzi-himmelrich", category: "eat", sort_order: 40,
    name: "Pastarazzi Himmelrich",
    tagline: "Handmade pasta & pizza",
    address: "Claridenstrasse 2, 6003 Luzern",
    bus_route: "Bus 14 → Paulusplatz, 4 min walk",
    why_we_love_it: "Seasonal ravioli mix",
  },
  {
    ...BASE,
    id: 5, slug: "nooch-mattenhof", category: "eat", sort_order: 50,
    name: "Nooch Mattenhof",
    tagline: "Asian street food & sushi",
    address: "Am Mattenhof 16a, 6010 Kriens",
    bus_route: "10 min walk from Mattenhof station",
    why_we_love_it: "Infused water «Phoenix and Passion»",
  },
  {
    ...BASE,
    id: 6, slug: "majorelle-neustadt", category: "eat", sort_order: 60,
    name: "Majorelle Neustadt",
    tagline: "Moroccan cuisine",
    address: "Himmelrichstrasse 12, 6003 Luzern",
    bus_route: "Bus 14 → Paulusplatz, 4 min walk",
    why_we_love_it: "Fresh Moroccan mint tea or chai latte",
  },
  {
    ...BASE,
    id: 7, slug: "rest-helvetia", category: "eat", sort_order: 70,
    name: "Rest. Helvetia",
    tagline: "Swiss classics",
    address: "Waldstätterstrasse 9, 6003 Luzern",
    bus_route: "Bus 14 → Moosmatt, 3 min walk",
    why_we_love_it: "Farmhouse bratwurst & chocolate mousse",
  },
  {
    ...BASE,
    id: 8, slug: "wirtshaus-taube", category: "eat", sort_order: 80,
    name: "Wirtshaus Taube",
    tagline: "Lucerne recipes & Swiss classics",
    address: "Burgerstrasse 3, 6003 Luzern",
    bus_route: "Bus 14 → Pilatusplatz, 5 min walk",
    why_we_love_it: "Lucerne Kügelipastetli",
    tags: ["personal-favorites"],
  },
  {
    ...BASE,
    id: 9, slug: "mamma-leone", category: "eat", sort_order: 90,
    name: "Mamma Leone",
    tagline: "Italian · 14 Gault Millau points",
    address: "Mühlenplatz 12, 6004 Luzern",
    bus_route: "Bus 14 → Pilatusplatz, 8 min walk",
    why_we_love_it: "Carpaccio di barbabietola with burrata",
    tags: ["splurge", "reservation"],
  },
  {
    ...BASE,
    id: 10, slug: "rest-bayts", category: "eat", sort_order: 100,
    name: "Rest. Bayt's",
    tagline: "Vegan fine dining",
    address: "Bireggstrasse 24, 6003 Luzern",
    bus_route: "Bus 14 → Pauluskirche, turn left",
    why_we_love_it: "Let yourself be surprised",
    tags: ["vegetarian", "splurge"],
  },
  {
    ...BASE,
    id: 11, slug: "pizzeria-fratelli", category: "eat", sort_order: 110,
    name: "Pizzeria Fratelli",
    tagline: "Pizza in the neighbourhood",
    address: "Schweighotplatz 1, 6010 Kriens",
    walk_time_min: 5,
    why_we_love_it: "Quick & easy — always reliable",
    tags: ["budget", "walk-in"],
  },
  {
    ...BASE,
    id: 12, slug: "rest-fed", category: "eat", sort_order: 120,
    name: "Rest. FED",
    tagline: "Food-sharing experience",
    address: "Pilatusstrasse 46, 6003 Luzern",
    bus_route: "Bus 14 → Pilatusplatz, 3 min walk",
    why_we_love_it: "Homemade cherry lemonade",
    tags: ["romantic"],
  },
  {
    ...BASE,
    id: 13, slug: "grottino-1313", category: "eat", sort_order: 130,
    name: "Grottino 1313",
    tagline: "Surprise menu, Mediterranean",
    address: "Industriestrasse 7, 6005 Luzern",
    bus_route: "Bus 14 → Kantonalbank → Bus 6/7/8/21 → Werkhofstrasse",
    why_we_love_it: "4–5 course surprise menu — always recommended",
    tags: ["personal-favorites", "splurge", "reservation"],
  },
  {
    ...BASE,
    id: 14, slug: "jazzkantine", category: "eat", sort_order: 140,
    name: "Jazzkantine",
    tagline: "Tavolata, music & cocktails",
    address: "Grabenstrasse 8, 6002 Luzern",
    bus_route: "In the old town",
    why_we_love_it: "Sourdough bread with spread",
    tags: ["evening"],
  },
  {
    ...BASE,
    id: 15, slug: "himmelrich-terrace", category: "eat", sort_order: 150,
    name: "Himmelrich Terrace",
    tagline: "Panoramic views",
    address: "Schattenbergstrasse 107, 6010 Kriens",
    bus_route: "By car or ~30 min on foot",
    why_we_love_it: "The view from the terrace is magnificent",
    tags: ["view", "sunny-day"],
  },

  // ── DRINK ───────────────────────────────────────────────────────────────
  {
    ...BASE,
    id: 20, slug: "suite-rooftop", category: "drink", sort_order: 10,
    name: "Suite Rooftop",
    tagline: "Extravagant · breathtaking views",
    address: "Pilatusstrasse 3, 6003 Luzern",
    bus_route: "Above Starbucks at the train station",
    why_we_love_it: "Whiskey Sour",
    tags: ["personal-favorites", "view", "evening"],
  },
  {
    ...BASE,
    id: 21, slug: "montana-beach-club", category: "drink", sort_order: 20,
    name: "Montana Beach Club",
    tagline: "Elegant · Art Deco Hotel Montana rooftop",
    address: "Adligenswilerstrasse 22, 6006 Luzern",
    bus_route: "Bus 14 → Gärtnerstrasse → Abendweg, 5 min down",
    why_we_love_it: "Fantastic mocktails",
    tags: ["view", "sunset", "romantic"],
  },
  {
    ...BASE,
    id: 22, slug: "sunset-bar", category: "drink", sort_order: 30,
    name: "Sunset Bar",
    tagline: "Outdoor · lake & mountain views",
    address: "Seeburgstrasse 61, 6006 Luzern",
    bus_route: "Directly on the lake",
    why_we_love_it: "Mojito",
    tags: ["lake", "sunset", "sunny-day"],
  },
  {
    ...BASE,
    id: 23, slug: "central-kriens", category: "drink", sort_order: 40,
    name: "Central Kriens",
    tagline: "Coffee & drinks · perfect before Pilatus",
    bus_route: "5 min walk from Busschleife stop",
    why_we_love_it: "Gin Tea",
    tags: ["morning"],
  },

  // ── CULTURE (Sport & Activities) ────────────────────────────────────────
  {
    ...BASE,
    id: 30, slug: "padelta-kriens", category: "culture", sort_order: 10,
    name: "Padelta Kriens",
    tagline: "Squash · Tennis · Padel",
    address: "Schlundstrasse, 6010 Kriens",
    bus_route: "Bus 14 → Horw, 8 min walk",
  },
  {
    ...BASE,
    id: 31, slug: "city-boulder", category: "culture", sort_order: 20,
    name: "City Boulder",
    tagline: "Bouldering hall",
    bus_route: "Directly opposite Padelta",
  },
  {
    ...BASE,
    id: 32, slug: "bowling-universe", category: "culture", sort_order: 30,
    name: "Bowling Universe",
    tagline: "Bowling · Billiards · Darts",
    address: "Industriestrasse 15, 6010 Kriens",
    bus_route: "Bus 14 → Horw, 12 min walk",
    tags: ["family-friendly", "rainy-day"],
  },
  {
    ...BASE,
    id: 33, slug: "cinema-bourbaki", category: "culture", sort_order: 40,
    name: "Cinema Bourbaki",
    tagline: "Arthouse & Swiss films",
    address: "Löwenplatz 11, 6004 Luzern",
    bus_route: "Bus 14 → Lucerne Wey, 4 min walk",
    tags: ["rainy-day", "evening"],
  },
  {
    ...BASE,
    id: 34, slug: "glacier-garden", category: "culture", sort_order: 50,
    name: "Glacier Garden",
    tagline: "Mirror Maze & Ice Age history",
    address: "Denkmalstrasse 4a, 6006 Luzern",
    bus_route: "Bus 14 → Bourbaki, walk past Lion Monument",
    tags: ["family-friendly", "rainy-day"],
  },
  {
    ...BASE,
    id: 35, slug: "beach-bath-lido", category: "culture", sort_order: 60,
    name: "Beach Bath Lido",
    tagline: "Swimming · volleyball · paddleboarding",
    address: "Lidostrasse 6A, 6006 Luzern",
    bus_route: "Bus 14 → Luzern station → Bus 6/8 → Verkehrshaus-Lido",
    tags: ["sunny-day", "lake", "family-friendly"],
  },
  {
    ...BASE,
    id: 36, slug: "lake-bath-lucerne", category: "culture", sort_order: 70,
    name: "Lake Bath Lucerne",
    tagline: "Historic Seebad since 1885 · wooden decks",
    address: "Nationalquai, 6006 Luzern",
    bus_route: "Bus 14 → Luzern Wey, 8 min walk",
    tags: ["sunny-day", "lake"],
  },
  {
    ...BASE,
    id: 37, slug: "kkl-lucerne", category: "culture", sort_order: 80,
    name: "KKL Lucerne",
    tagline: "Classical music · art · theater",
    address: "Europaplatz 1, 6005 Luzern",
    bus_route: "Next to the train station",
    why_we_love_it: "Film with live music by the 21st Century Orchestra",
    tags: ["evening", "rainy-day"],
  },
  {
    ...BASE,
    id: 38, slug: "chapel-bridge", category: "culture", sort_order: 90,
    name: "Chapel Bridge",
    tagline: "Iconic landmark — a must",
    address: "Altstadt, Luzern",
    bus_route: "Bus 14 → Luzern station, look toward old town",
    tags: ["photo-spot"],
  },
  {
    ...BASE,
    id: 39, slug: "conservatory", category: "culture", sort_order: 100,
    name: "Conservatory",
    tagline: "Best view over the lake — insider tip",
    address: "Dreilindenstrasse 93, 6006 Luzern",
    bus_route: "Bus 14 → Conservatory, walk up stairs",
    why_we_love_it: "Bring a picnic",
    tags: ["personal-favorites", "view", "hidden-gem", "photo-spot"],
  },
  {
    ...BASE,
    id: 40, slug: "lion-monument", category: "culture", sort_order: 110,
    name: "Lion Monument",
    tagline: "Moving symbol of bravery",
    address: "Denkmalstrasse 4, 6002 Luzern",
    bus_route: "Bus 14 → Luzern Wey, past Bourbaki",
    why_we_love_it: "«The saddest piece of stone in the world» — Mark Twain",
    tags: ["photo-spot"],
  },
  {
    ...BASE,
    id: 41, slug: "musegg-wall", category: "culture", sort_order: 120,
    name: "Musegg Wall",
    tagline: "Medieval city wall · 9 towers",
    address: "Denkmalstrasse 4, 6002 Luzern",
    bus_route: "Bus 14 → Pilatusplatz, 10 min through old town",
    why_we_love_it: "Aperitif at «Hinter Musegg»",
    tags: ["photo-spot", "view"],
  },

  // ── HIKE (Mountains & Viewpoints) ───────────────────────────────────────
  {
    ...BASE,
    id: 50, slug: "mount-pilatus", category: "hike", sort_order: 10,
    name: "Mount Pilatus",
    tagline: "World's steepest cogwheel railway · hiking · paragliding",
    address: "Schlossweg 1, 6010 Kriens",
    bus_route: "Bus 21 from Kriens Steinmatt → Kriens Zentrum → valley station",
    tags: ["personal-favorites", "view", "mountain", "photo-spot"],
  },
  {
    ...BASE,
    id: 51, slug: "mount-titlis", category: "hike", sort_order: 20,
    name: "Mount Titlis",
    tagline: "Glacier experience · 3,000 m altitude · Rotair cable car",
    address: "Engelberg",
    bus_route: "Bus 14 → Luzern station → IRLEX express to Engelberg",
    tags: ["view", "mountain", "photo-spot"],
  },
  {
    ...BASE,
    id: 52, slug: "mount-rigi", category: "hike", sort_order: 30,
    name: "Mount Rigi",
    tagline: "Queen of the Mountains · 360° panoramic view",
    address: "Vitznau",
    bus_route: "Train Lucerne → Arth-Goldau → cog railway, OR boat → Vitznau",
    tags: ["view", "mountain", "photo-spot"],
  },
  {
    ...BASE,
    id: 53, slug: "stanserhorn", category: "hike", sort_order: 40,
    name: "Stanserhorn",
    tagline: "Cabrio-Bahn — world's first open upper deck cable car",
    address: "Stans",
    bus_route: "Walk to Mattenhof → S4 to Stans → walk to valley station",
    tags: ["view", "mountain", "hidden-gem"],
  },
  {
    ...BASE,
    id: 54, slug: "klewendalp", category: "hike", sort_order: 50,
    name: "Klewendalp",
    tagline: "Scenic walks · family-friendly · gondola",
    address: "Beckenried",
    bus_route: "Only by car — large parking at valley station",
    tags: ["family-friendly", "mountain"],
  },
  {
    ...BASE,
    id: 55, slug: "lakeview-biregg", category: "hike", sort_order: 60,
    name: "Lakeview Biregg",
    tagline: "On foot from the apartment — insider tip",
    address: "Auf Oberrüti 19, 6048 Horw",
    bus_route: "Start at Nidfeld, return via Bus 14",
    why_we_love_it: "Walk through Allmend stadium → Waldegg forest → Bireggwald → Felmis → Seeblick Oberrüti → Tribschen → lake shore · 5–7 km · Bring a picnic",
    tags: ["personal-favorites", "hidden-gem", "view", "lake"],
  },
  {
    ...BASE,
    id: 56, slug: "ship-to-buergenstock", category: "hike", sort_order: 70,
    name: "Ship to Bürgenstock",
    tagline: "Boat trip · panoramic views · funicular",
    address: "Landungsbrücke 1, 6003 Luzern",
    bus_route: "Bus 14 → Luzern station, pier in front",
    tags: ["view", "lake", "romantic"],
  },
  {
    ...BASE,
    id: 57, slug: "ship-to-brunnen", category: "hike", sort_order: 80,
    name: "Ship to Brunnen",
    tagline: "3 hours of pure comfort · alpine scenery",
    address: "Landungsbrücke 1, 6003 Luzern",
    bus_route: "Same pier as Bürgenstock boat",
    tags: ["lake", "view"],
  },
];

export function getByCategory(category: string): Recommendation[] {
  return RECOMMENDATIONS.filter((r) => r.category === category && r.published)
    .sort((a, b) => a.sort_order - b.sort_order);
}

export function getBySlug(category: string, slug: string): Recommendation | undefined {
  return RECOMMENDATIONS.find((r) => r.category === category && r.slug === slug && r.published);
}

export function countByCategory(category: string): number {
  return RECOMMENDATIONS.filter((r) => r.category === category && r.published).length;
}
