import type { Recommendation } from "@/types/recommendation";

const BASE: Omit<Recommendation, "id" | "slug" | "category" | "name" | "tagline" | "sort_order"> = {
  description: null,
  why_we_love_it: null,
  address: null,
  lat: null,
  lng: null,
  website: null,
  phone: null,
  opening_hours: null,
  price_range: null,
  walk_time_min: null,
  bike_time_min: null,
  bus_route: null,
  season: [],
  tags: [],
  image_url: null,
  image_credit: null,
  source_url: null,
  google_place_id: null,
  image_reference: null,
  image_attribution: null,
  published: true,
  created_at: "",
  updated_at: "",
};

export const RECOMMENDATIONS: Recommendation[] = [
  // ── EAT ────────────────────────────────────────────────────────────────
  {
    ...BASE,
    id: 1, slug: "two-hands", category: "eat", sort_order: 10,
    name: "Two Hands",
    tagline: "Creative cosmopolitan cuisine",
    address: "Waldstätterstrasse 6, 6003 Luzern",
    description: "Two Hands in Lucerne stands for creative, cosmopolitan cuisine with regional roots. The restaurant focuses on fresh, seasonal ingredients and combines them to create sophisticated dishes with international influences. The modern yet cozy ambiance creates a relaxed atmosphere where enjoyment and hospitality take center stage. Whether for a relaxed lunch, a romantic dinner, or a special occasion, Two Hands offers culinary experiences that will linger in your memory for a long time to come.",
    bus_route: "Take bus no. 14 to Moosmatt, then walk 4 minutes to Neustadt.",
    why_we_love_it: "Chai tea and homemade pancakes",
    tags: ["personal-favorites"],
  },
  {
    ...BASE,
    id: 2, slug: "melissas-kitchen", category: "eat", sort_order: 20,
    name: "Melissa's Kitchen",
    tagline: "Homemade, fresh, organic",
    address: "Hirschengraben 19, 6003 Luzern",
    description: "Melissa's Kitchen in Lucerne delights guests with homemade, fresh, and healthy dishes inspired by international flavors. Here, creative cuisine meets warm hospitality. Whether breakfast, lunch, or afternoon cake, everything is prepared with love, often using regional and organic ingredients. The cozy atmosphere invites you to linger and makes Melissa's Kitchen a place where enjoyment, quality, and a feel-good atmosphere harmonize perfectly.",
    bus_route: "Take bus no. 14 to Pilatusplatz, then walk for 5 minutes.",
    why_we_love_it: "On Sundays and public holidays, there is a large, delicious brunch buffet.",
  },
  {
    ...BASE,
    id: 3, slug: "karls-kraut", category: "eat", sort_order: 30,
    name: "Karls Kraut",
    tagline: "Vegan cuisine",
    address: "St. Karliquai 7, 6004 Luzern",
    description: "Karls Kraut in Lucerne stands for creative, plant-based cuisine full of flavor and variety. Here, fresh, seasonal ingredients are transformed into colorful bowls, sophisticated vegetable dishes, and homemade specialties – all vegetarian or vegan. The charming, cozy atmosphere invites you to linger, while the changing menu always has new culinary surprises in store. Karls Kraut is the perfect place for conscious enjoyment that is healthy, sustainable, and simply delicious.",
    bus_route: "Take bus no. 14 to Pilatusplatz, then walk 10 minutes to the old town, past Mühlenplatz and along the Reuss river.",
    why_we_love_it: "Brunch is served every second and fourth Sunday of the month and is very delicious.",
    tags: ["vegetarian"],
  },
  {
    ...BASE,
    id: 4, slug: "pastarazzi-himmelrich", category: "eat", sort_order: 40,
    name: "Pastarazzi Himmelrich",
    tagline: "Great pizza & pasta",
    address: "Claridenstrasse 2, 6003 Luzern",
    description: "Pastarazzi in Himmelrich, Lucerne, is all about fresh, handmade pasta in lots of creative ways. They cook with high-quality, often local ingredients every day—from classic recipes to surprising new creations. The modern, cozy atmosphere invites you to linger, while the open kitchen and warm service ensure an authentic experience. Whether for a quick lunch or a relaxed dinner, Pastarazzi combines Italian culinary culture with Lucerne charm.",
    bus_route: "Take bus no. 14 to the Paulusplatz bus stop, then walk 4 minutes to Neustadt.",
    why_we_love_it: "Seasonal ravioli mix",
  },
  {
    ...BASE,
    id: 5, slug: "nooch-mattenhof", category: "eat", sort_order: 50,
    name: "Nooch Mattenhof",
    tagline: "Asian street food & sushi",
    address: "Am Mattenhof 16a, 6010 Kriens",
    description: "Nooch in Kriens brings Asian street food vibes to a modern, urban setting. The menu features sushi, curries, noodle and rice bowls – freshly prepared and full of flavor. Colorful cocktails and creative desserts round out the experience. With its stylish interior and relaxed atmosphere, Nooch is the perfect place to enjoy moments of pleasure with friends, family, or as a couple. Here, culinary diversity from Asia meets a casual lifestyle in the heart of Kriens.",
    bus_route: "It is a 10-minute walk from Mattenhof station in Kriens.",
    why_we_love_it: "Infused Water \"Phoenix and Passion\"",
  },
  {
    ...BASE,
    id: 6, slug: "majorelle-neustadt", category: "eat", sort_order: 60,
    name: "Majorelle Neustadt",
    tagline: "Moroccan cuisine",
    address: "Himmelrichstrasse 12, 6003 Luzern",
    description: "Majorelle in Lucerne whisks guests away to a world of Moroccan flavors and colors. Aromatic tagines, spicy couscous variations, and oriental mezze are served in an atmospheric setting – everything is freshly prepared and rich in spices. Inspired by the famous Jardin Majorelle in Marrakesh, the restaurant combines culinary authenticity with stylish hospitality. A place for enjoyable evenings, convivial gatherings and a little break from everyday life in the heart of Lucerne.",
    bus_route: "Take bus no. 14 to the Paulusplatz bus stop, then walk 4 minutes to Neustadt.",
    why_we_love_it: "Fresh Moroccan mint tea or homemade chai latte",
  },
  {
    ...BASE,
    id: 7, slug: "rest-helvetia", category: "eat", sort_order: 70,
    name: "Rest. Helvetia",
    tagline: "Swiss classics",
    address: "Waldstätterstrasse 9, 6003 Luzern",
    description: "The Helvetia restaurant in Lucerne combines traditional Swiss cuisine with contemporary sophistication. The focus here is on classics such as rösti and fresh fish dishes – prepared with regional ingredients and great attention to detail. The stylish, cozy atmosphere invites both locals and visitors to linger. With its warm service and select wine list, Helvetia is a place for authentic enjoyment and convivial moments in the heart of Lucerne.",
    bus_route: "Take bus no. 14 to Moosmatt, then walk 3 minutes to Neustadt.",
    why_we_love_it: "Farmhouse bratwurst and chocolate mousse",
  },
  {
    ...BASE,
    id: 8, slug: "wirtshaus-taube", category: "eat", sort_order: 80,
    name: "Wirtshaus Taube",
    tagline: "Lucerne recipes & Swiss classics",
    address: "Burgerstrasse 3, 6003 Luzern",
    description: "The Wirtshaus Taube in Lucerne stands for genuine hospitality and honest, down-to-earth cuisine. Seasonal specialities, Swiss classics and fine home-style dishes are served in a cosy, rustic atmosphere – always freshly prepared and often using regional products. Whether for lunch, dinner, or a get-together with friends, the Traube offers a warm, inviting atmosphere where you will immediately feel at home. Here, tradition meets warmth—a piece of Lucerne's way of life.",
    bus_route: "Take bus no. 14 to Pilatusplatz, then walk 5 minutes toward the Reuss River.",
    why_we_love_it: "A typical Lucerne dish, Lucerne Kügelipastetli",
    tags: ["personal-favorites"],
  },
  {
    ...BASE,
    id: 9, slug: "mamma-leone", category: "eat", sort_order: 90,
    name: "Mamma Leone",
    tagline: "Italian · 14 Gault Millau points",
    address: "Mühlenplatz 12, 6004 Luzern",
    description: "Mamma Leone in Lucerne brings the authentic taste of Italy to your plate. Fresh pasta, crispy stone-baked pizzas, and homemade desserts are prepared with the finest ingredients and lots of amore. The Mediterranean atmosphere, friendly service, and exquisite wine selection invite you to linger—whether for a relaxed lunch, a romantic dinner, or a cheerful get-together with friends. Mamma Leone is a piece of Italy in the heart of Lucerne that combines enjoyment and joie de vivre. 14 Gault Millau points",
    bus_route: "Take bus no. 14 to Pilatusplatz, then walk 8 minutes to the old town.",
    why_we_love_it: "Carpaccio di barbabietola (beetroot carpaccio with burrata)",
    tags: ["splurge", "reservation"],
  },
  {
    ...BASE,
    id: 10, slug: "rest-bayts", category: "eat", sort_order: 100,
    name: "Rest. Bayt's",
    tagline: "Vegan fine dining",
    address: "Bireggstrasse 24, 6003 Luzern",
    description: "Bayts in Lucerne offers purely plant-based culinary experiences of the highest standard. A multi-course menu showcasing vegetables in creative ways is served in an elegant yet relaxed atmosphere. The dishes surprise with sophisticated flavor combinations, accompanied by carefully selected wines or non-alcoholic pairings. Seasonal ingredients, friendly service, and a personal touch make Bayts a hotspot for modern, sustainable fine dining in the heart of Lucerne.",
    bus_route: "Take bus no. 14 to Paulusplatz, then walk toward Pauluskirche and turn left into the neighborhood.",
    why_we_love_it: "Let yourself be surprised",
    tags: ["vegetarian", "splurge"],
  },
  {
    ...BASE,
    id: 11, slug: "pizzeria-fratelli", category: "eat", sort_order: 110,
    name: "Pizzeria Fratelli",
    tagline: "Pizza in the neighbourhood",
    address: "Schweighofplatz 1, 6010 Kriens",
    walk_time_min: 5,
    description: "Pizzeria Fratelli in Kriens is synonymous with authentic Italian cuisine and family hospitality. Here, crispy pizzas are baked in a stone oven, and fresh pasta and traditional antipasti are prepared using the finest ingredients. The cozy Mediterranean atmosphere invites you to linger—whether for a relaxed lunch, a romantic dinner, or a convivial get-together with friends. Fratelli combines Italian joie de vivre, quality, and warm service in the heart of Kriens.",
    bus_route: "A 5-minute walk from the apartment. It's best to use Google Maps.",
    why_we_love_it: "When you want a quick and easy solution",
    tags: ["budget", "walk-in"],
  },
  {
    ...BASE,
    id: 12, slug: "rest-fed", category: "eat", sort_order: 120,
    name: "Rest. FED",
    tagline: "Food-sharing experience",
    address: "Pilatusstrasse 46, 6003 Luzern",
    description: "FED in Lucerne combines modern design with innovative cuisine and a food-sharing concept. The restaurant focuses on fresh, regional ingredients and uses them to create creative dishes with international influences. Whether for a relaxed lunch, a stylish dinner, or cocktails at the bar, FED offers a culinary experience in an urban, elegant atmosphere. The open kitchen and attentive service make every visit special. A meeting place for connoisseurs who appreciate good food, a stylish ambience, and lively hospitality.",
    bus_route: "Take bus no. 14 to Pilatusplatz, then walk 3 minutes across the intersection.",
    why_we_love_it: "Homemade cherry lemonade",
    tags: ["romantic"],
  },
  {
    ...BASE,
    id: 13, slug: "grottino-1313", category: "eat", sort_order: 130,
    name: "Grottino 1313",
    tagline: "Surprise menu, Mediterranean",
    address: "Industriestrasse 7, 6005 Luzern",
    description: "Grottino 1313 in Lucerne is a culinary gem with charming industrial charm. There is no fixed menu here – whatever is in season and available at the market is what is cooked. Mediterranean-inspired dishes, fresh and prepared with love, are served in a convivial atmosphere at long wooden tables. Grottino stands for shared enjoyment, honest cuisine, and warm hospitality. It's a place where you feel like you're among friends and are surprised every time you visit.",
    bus_route: "Take bus no. 14 to Kantonalbank, walk 2 minutes to the next bus stop (around the corner on the right), then take bus no. 6, 7, 8, or 21 to Werkhofstrasse, and walk 4 minutes to the restaurant.",
    why_we_love_it: "This Mediterranean restaurant offers a 4 or 5-course surprise menu in tavolata style. It is always very busy, so reservations are recommended.",
    tags: ["personal-favorites", "splurge", "reservation"],
  },
  {
    ...BASE,
    id: 14, slug: "jazzkantine", category: "eat", sort_order: 140,
    name: "Jazzkantine",
    tagline: "Tavolata, music & cocktails",
    address: "Grabenstrasse 8, 6002 Luzern",
    description: "The Jazzkantine in Lucerne is a lively meeting place for music and cocktail lovers. Creative drinks and selected wines are served in a relaxed, stylish atmosphere. With its varied program and charming service, the Jazzkantine is an integral part of Lucerne's nightlife. The restaurant has great options for vegetarians.",
    bus_route: "In the old town; the Jazzkantine offers delicious lunch menus or sourdough bread with spreads for a quick bite!",
    why_we_love_it: "Sourdough bread with spread",
    tags: ["evening"],
  },
  {
    ...BASE,
    id: 15, slug: "himmelrich-terrace", category: "eat", sort_order: 150,
    name: "Himmelrich Terrace",
    tagline: "Great view",
    address: "Schattenbergstrasse 107, 6010 Kriens",
    description: "The Himmelrich restaurant in Lucerne combines modern, uncomplicated cuisine with a cozy atmosphere. The menu features seasonal dishes made from fresh, regional ingredients – from creative bowls and crisp salads to hearty classics. The stylish, bright interior and relaxed atmosphere make it the ideal meeting place for lunch, after-work drinks, or a relaxed dinner. With friendly service and a varied menu, Himmelrich is a popular place to enjoy good food in the heart of the neighborhood of the same name.",
    bus_route: "Accessible by car via Kriens, or on foot up the Pilatus, approx. 30 minutes.",
    why_we_love_it: "The view from the terrace is magnificent.",
    tags: ["view", "sunny-day"],
  },

  // ── DRINK ───────────────────────────────────────────────────────────────
  {
    ...BASE,
    id: 20, slug: "suite-rooftop", category: "drink", sort_order: 10,
    name: "Suite Rooftop",
    tagline: "Extravagant · breathtaking views",
    address: "Pilatusstrasse 3, 6003 Luzern",
    description: "The Suite Rooftop Bar in Lucerne offers breathtaking views of the lake, city, and mountains—perfect for unforgettable evenings. In an elegant, modern atmosphere, the team serves creative cocktails, fine wines, and delicious snacks. At sunset, the roof terrace is transformed into a magical place where music, lights, and views merge into a unique experience. The Suite Rooftop Bar is the ideal meeting place for stylish drinks and special moments high above the rooftops of Lucerne.",
    bus_route: "Directly at the train station, above Starbucks.",
    why_we_love_it: "Whiskey Sour",
    tags: ["personal-favorites", "view", "evening"],
  },
  {
    ...BASE,
    id: 21, slug: "montana-beach-club", category: "drink", sort_order: 20,
    name: "Montana Beach Club",
    tagline: "Elegant · Art Deco Hotel Montana rooftop",
    address: "Adligenswilerstrasse 22, 6006 Luzern",
    description: "The Montana Beach Club in Lucerne combines a vacation feeling with spectacular views of Lake Lucerne and the Alps. On the roof terrace of the Art Deco Hotel Montana, guests can enjoy comfortable lounges, cool drinks, refreshing cocktails, and summer snacks. Sand under your feet, relaxing music, and sparkling water create a unique atmosphere in the middle of the city. Whether for sunbathing during the day or sundowners in the evening, the Montana Beach Club is an exclusive hotspot for summer enjoyment.",
    bus_route: "Take bus no. 14 to Gärtnerstrasse, then walk down Abendweg for 5 minutes. Or change at Lucerne train station to bus no. 8 or 6 to Lucerne Casino-Palace, where you will find the lift directly to the Montana on the other side of the street.",
    why_we_love_it: "The fantastic mocktails",
    tags: ["view", "sunset", "romantic"],
  },
  {
    ...BASE,
    id: 22, slug: "sunset-bar", category: "drink", sort_order: 30,
    name: "Sunset Bar",
    tagline: "Outdoor · lake & mountain views",
    address: "Seeburgstrasse 61, 6006 Luzern",
    description: "The Sunset Bar in Lucerne offers stunning views of Lake Lucerne and the surrounding mountains – especially magical at sunset. Refreshing cocktails, fine wines, and light snacks are served in a relaxed atmosphere. Whether after work, as a romantic meeting place or for a cozy evening with friends, the Sunset Bar is the perfect place to end the day in style and enjoy the golden hours of Lucerne.",
    bus_route: "This location is outdoors. There are various seating options and snack stands. The Sunset Bar is located directly on the lake with a view of the mountains.",
    why_we_love_it: "Mojito",
    tags: ["lake", "sunset", "sunny-day"],
  },
  {
    ...BASE,
    id: 23, slug: "central-kriens", category: "drink", sort_order: 40,
    name: "Central Kriens",
    tagline: "Coffee & drinks · perfect before Pilatus",
    address: "Waldheimstrasse 1, 6010 Kriens",
    description: "The Central in Kriens is a popular meeting place for good food and convivial moments. Seasonal dishes, Swiss classics, and international specialties are served in a modern, cozy atmosphere—freshly prepared with great attention to detail. Whether for lunch, dinner, or a drink at the bar, the Central offers a welcoming atmosphere and friendly service and is ideal for spending time with family, friends, or colleagues in the heart of Kriens.",
    bus_route: "Walk 5 minutes to the Sternmatt bus stop, take bus no. 16 or 21 to the Busschleife stop. The restaurant is located across the street on the corner.",
    why_we_love_it: "Gin Tea",
    tags: ["morning"],
  },

  // ── CULTURE (Sport & Activities) ────────────────────────────────────────
  {
    ...BASE,
    id: 30, slug: "padelta-kriens", category: "culture", sort_order: 10,
    name: "Padelta Kriens",
    tagline: "Squash · Tennis · Padel",
    address: "Schlundstrasse, 6010 Kriens",
    description: "Padelta in Kriens is the place to be for anyone who loves padel or wants to give it a try. The modern facility offers well-maintained courts, professional equipment, and a relaxed, sporty atmosphere. Whether you're a beginner or a pro, there's something for everyone here. In addition to free play times, there are also courses, tournaments, and events that strengthen the sense of community. Padelta combines sport, fun, and social interaction into an active experience for young and old alike.",
    bus_route: "Take bus no. 14 towards Horw and get off at the Grabenhof stop. Walk 8 minutes along the side street to the roundabout, then turn left and follow the stream.",
  },
  {
    ...BASE,
    id: 31, slug: "city-boulder", category: "culture", sort_order: 20,
    name: "City Boulder",
    tagline: "Bouldering hall",
    description: "City Boulder in Kriens is the perfect place for anyone who wants to experience climbing without ropes in an urban atmosphere. The modern bouldering hall offers varied routes for beginners to professionals, regular new challenges, and a welcoming community. With a cozy lounge, snacks, and drinks, the sport also becomes a social experience. Whether for a quick workout or an entire afternoon, City Boulder combines exercise, fun, and community at the highest level.",
    bus_route: "Cross the street.",
  },
  {
    ...BASE,
    id: 32, slug: "bowling-universe", category: "culture", sort_order: 30,
    name: "Bowling Universe",
    tagline: "Bowling · Billiards · Darts",
    address: "Industriestrasse 15, 6010 Kriens",
    description: "Bowling Universum in Kriens offers fun and action for all ages. Beginners and pros alike can test their accuracy on modern lanes, accompanied by lively music and a great atmosphere. In addition to bowling, billiards, arcade games, and a wide range of snacks and drinks provide plenty of variety. Whether it's a family outing, an evening with friends, or a company event, Bowling Universum combines sporting competition with socializing in a relaxed atmosphere.",
    bus_route: "Take bus no. 14 towards Horw, get off at the Oberkuonimatt bus stop, cross the road past the large car tent and walk along the road for 4 minutes. Or it's a 12-minute walk from Nidfeld!",
    tags: ["family-friendly", "rainy-day"],
  },
  {
    ...BASE,
    id: 33, slug: "cinema-bourbaki", category: "culture", sort_order: 40,
    name: "Cinema Bourbaki",
    tagline: "Arthouse & Swiss films",
    address: "Löwenplatz 11, 6004 Luzern",
    description: "The Bourbaki cinema in Lucerne is a charming arthouse cinema in the historic Bourbaki Panorama. It shows carefully curated films – from current arthouse productions to classics – mostly in their original language. With comfortable seats, modern technology, and an intimate atmosphere, every visit to the cinema is a special experience. The inviting foyer with bar is the perfect place to linger before or after the show, making the Bourbaki a cultural meeting place for cineastes and curious minds alike.",
    bus_route: "Take bus no. 14 to Lucerne Wey, then walk for 4 minutes.",
    tags: ["rainy-day", "evening"],
  },
  {
    ...BASE,
    id: 34, slug: "glacier-garden", category: "culture", sort_order: 50,
    name: "Glacier Garden",
    tagline: "Mirror Maze & Ice Age history",
    address: "Denkmalstrasse 4a, 6006 Luzern",
    description: "The Glacier Garden in Lucerne is a unique natural and cultural monument that combines impressive traces of the Ice Age with an exciting history. Visitors can discover glacier pots, fossils, and rock formations that are millions of years old, as well as interactive exhibitions on the history of the Earth. The historic Hall of Mirrors and the observation tower offer additional special experiences. With its mix of science, nature, and architecture, the Glacier Garden is a fascinating destination for young and old alike.",
    bus_route: "Take bus no. 14 to Lucerne Wey, walk past Bourbaki and continue on a side street until you reach the Lion Monument. The Glacier Garden is located there.",
    tags: ["family-friendly", "rainy-day"],
  },
  {
    ...BASE,
    id: 35, slug: "beach-bath-lido", category: "culture", sort_order: 60,
    name: "Beach Bath Lido",
    tagline: "Swimming · volleyball · paddleboarding",
    address: "Lidostrasse 6A, 6006 Luzern",
    description: "The Lido beach in Lucerne is a summer hotspot right on Lake Lucerne. With its extensive sandy beach, large sunbathing lawn, and clear water, it is ideal for swimming, sunbathing, and relaxing. Sporty guests can enjoy beach volleyball courts, a diving tower, or stand-up paddleboarding, while children can splash around safely in the shallow waters near the shore. Refreshments and snacks are available. The Lido combines a vacation feeling with urban proximity – perfect for hot days.",
    bus_route: "Take bus no. 14 to Lucerne train station, then bus no. 6 or 8 to Verkehrshaus-Lido, then walk 7 minutes along the lake and past the Verkehrshaus.",
    tags: ["sunny-day", "lake", "family-friendly"],
  },
  {
    ...BASE,
    id: 36, slug: "lake-bath-lucerne", category: "culture", sort_order: 70,
    name: "Lake Bath Lucerne",
    tagline: "Historic Seebad since 1885 · wooden decks",
    address: "Nationalquai, 6006 Luzern",
    description: "The Seebad Luzern is a charming, historic bathing establishment directly on Lake Lucerne, which has been part of summer city life since 1885. On the wooden complex with two separate bathing areas for men and women and a shared swimming area, you can relax in the lake, sunbathe, and enjoy the view of Mount Pilatus and Mount Rigi. A bar and restaurant provide refreshments and light meals, while deck chairs and sun decks invite you to linger. A place with nostalgic flair and a holiday feeling in the heart of Lucerne.",
    bus_route: "Take bus no. 14 to the Luzern Wey stop, then walk 8 minutes along the lake.",
    tags: ["sunny-day", "lake"],
  },
  {
    ...BASE,
    id: 37, slug: "kkl-lucerne", category: "culture", sort_order: 80,
    name: "KKL Lucerne",
    tagline: "Classical music · art · theater",
    address: "Europaplatz 1, 6005 Luzern",
    description: "The KKL Luzern is an architectural masterpiece by Jean Nouvel and one of Switzerland's most important cultural centers. Located directly on Lake Lucerne, it impresses with its spectacular architecture and excellent acoustics. World-renowned festivals such as the Lucerne Festival, high-caliber concerts, exhibitions, and conferences take place here. The interplay of art, music, cuisine, and a unique location makes the KKL a cultural landmark and meeting place for guests from all over the world.",
    bus_route: "The KKL is right next to Lucerne train station. It is a large building with lots of windows, directly on the lake.",
    why_we_love_it: "Film with live music by the 21st Century Orchestra",
    tags: ["evening", "rainy-day"],
  },
  {
    ...BASE,
    id: 38, slug: "chapel-bridge", category: "culture", sort_order: 90,
    name: "Chapel Bridge",
    tagline: "Iconic landmark — a must",
    address: "Altstadt, Luzern",
    description: "The Chapel Bridge is Lucerne's landmark and one of the oldest covered wooden bridges in Europe. Built in the 14th century, it connects the old town with the new town and impresses with historical triangular paintings depicting scenes from the city's history. Together with the striking water tower, it forms a picturesque ensemble that is one of the most photographed sights in Switzerland. A walk across the Chapel Bridge is a must for every visitor to Lucerne.",
    bus_route: "Take bus no. 14 to Lucerne train station, then look towards the old town. The bridge is impossible to miss.",
    tags: ["photo-spot"],
  },
  {
    ...BASE,
    id: 39, slug: "conservatory", category: "culture", sort_order: 100,
    name: "Conservatory",
    tagline: "Best view over the lake — insider tip",
    address: "Dreilindenstrasse 93, 6006 Luzern",
    description: "The Lucerne Conservatory, nestled in the idyllic Dreilindenpark, combines music, education, and culture in a unique setting. The historic park, located high above the city, offers breathtaking views of Lucerne, Lake Lucerne, and the Alps. Surrounded by old trees, sculptures, and well-kept green spaces, it invites you to stroll, linger, and be inspired. The conservatory itself is a place of musical excellence where talent is nurtured and cultural events can be enjoyed in a special atmosphere.",
    bus_route: "Take bus no. 14 to Lucerne Conservatory, then walk up the stairs on the other side of the street.",
    why_we_love_it: "Bring a picnic and enjoy the breathtaking view. There is no restaurant at the conservatory.",
    tags: ["personal-favorites", "view", "hidden-gem", "photo-spot"],
  },
  {
    ...BASE,
    id: 40, slug: "lion-monument", category: "culture", sort_order: 110,
    name: "Lion Monument",
    tagline: "Moving symbol of bravery",
    address: "Denkmalstrasse 4, 6002 Luzern",
    description: "The Lion Monument in Lucerne is one of Switzerland's most famous monuments and a moving symbol of bravery and loyalty. It commemorates the Swiss guards who fell in Paris during the French Revolution in 1792. The dying lion, carved into a rock face, impresses with its expressiveness and emotional depth. Surrounded by a peaceful park, the monument is a place of tranquility and reflection—and an important part of Lucerne's city history.",
    bus_route: "Take bus no. 14 to Lucerne Wey, walk past Bourbaki and continue on a side street until you reach the Lion Monument. The Glacier Garden is also located there.",
    tags: ["photo-spot"],
  },
  {
    ...BASE,
    id: 41, slug: "musegg-wall", category: "culture", sort_order: 120,
    name: "Musegg Wall",
    tagline: "Medieval city wall · 9 towers",
    address: "Denkmalstrasse 4, 6002 Luzern",
    description: "The Musegg Wall in Lucerne is a well-preserved section of the historic city fortifications dating back to the 14th century and is one of the city's landmarks. Nine striking towers dominate the skyline, some of which can be climbed to enjoy impressive views of the old town, Lake Lucerne, and the surrounding mountains. Open in spring and summer, the Musegg Wall invites you to take a walk through history and experience the authentic atmosphere of medieval Lucerne.",
    bus_route: "Take bus no. 14 to Pilatusplatz, then walk through the old town for 10 minutes, across Mühlenplatz, past the Karls Kraut restaurant. There you will find the first tower of the Musegg Wall.",
    why_we_love_it: "Aperitif at the Buurebeizli Hinter Musegg",
    tags: ["photo-spot", "view"],
  },

  // ── HIKE (Mountains & Viewpoints) ───────────────────────────────────────
  {
    ...BASE,
    id: 50, slug: "mount-pilatus", category: "hike", sort_order: 10,
    name: "Mount Pilatus",
    tagline: "World's steepest cogwheel railway · hiking · paragliding",
    address: "Schlossweg 1, 6010 Kriens",
    description: "Mount Pilatus, Lucerne's local mountain, impresses with its striking silhouette and magnificent views of Lake Lucerne and the Alps. It can be easily reached by the world's steepest cogwheel railway or by gondola and cable car. Whether hiking, climbing, paragliding, or simply enjoying the panoramic terraces, Mount Pilatus offers experiences for every taste. In winter it is transformed into a small snow paradise, in summer into a nature and adventure destination for the whole family.",
    bus_route: "Take bus no. 21 from Kriens, Sternmatt (approx. 100 m from the apartment) to Kriens, Zentrum - Pilatus and walk to the valley station.",
    tags: ["personal-favorites", "view", "mountain", "photo-spot"],
  },
  {
    ...BASE,
    id: 51, slug: "mount-titlis", category: "hike", sort_order: 20,
    name: "Mount Titlis",
    tagline: "Glacier experience · 3,000 m altitude · Rotair cable car",
    address: "Engelberg",
    description: "The Titlis near Engelberg is a spectacular destination and a year-round highlight in Central Switzerland. The rotating Rotair cable car takes you up to over 3,000 meters, where breathtaking views, eternal snow, and glacier experiences await. Visitors can cross the Cliff Walk – Europe's highest suspension bridge – hike on the glacier or simply enjoy the mountain scenery. In winter, the Titlis attracts visitors with its varied ski slopes, while in summer it offers hiking trails and adventure activities.",
    bus_route: "Take bus no. 14 to Lucerne train station, from where the IRLEX express train runs directly to Engelberg. In Engelberg, a footpath leads to the valley station in 10 minutes.",
    tags: ["view", "mountain", "photo-spot"],
  },
  {
    ...BASE,
    id: 52, slug: "mount-rigi", category: "hike", sort_order: 30,
    name: "Mount Rigi",
    tagline: "Queen of the Mountains · 360° panoramic view",
    address: "Vitznau",
    description: "The Rigi, also known as the \"Queen of the Mountains,\" offers a 360-degree panorama of Lake Lucerne, Lake Zug, and the Alps. It is a popular destination all year round and can be easily reached by cogwheel railway or cable car. In summer, idyllic hiking trails and picnic spots invite you to linger, while in winter, snowshoe trails and sleigh rides beckon. The combination of nature, views, and accessibility makes the Rigi a classic among Swiss mountains.",
    bus_route: "Take the train from Lucerne to Arth-Goldau and from there take the train up to the Rigi. Or take the boat from Lucerne to Vitznau and ride up on the historic cogwheel railway.",
    tags: ["view", "mountain", "photo-spot"],
  },
  {
    ...BASE,
    id: 53, slug: "stanserhorn", category: "hike", sort_order: 40,
    name: "Stanserhorn",
    tagline: "Cabrio-Bahn — world's first open upper deck cable car",
    address: "Stans",
    description: "The Stanserhorn in Nidwalden combines nature and technological history in a unique way. The journey begins with a nostalgic funicular railway and continues with the Cabrio Bahn – the world's first cable car with an open upper deck. At the top, visitors are greeted by breathtaking panoramic views of lakes and mountains, leisurely hiking trails, and the Stanserhorn restaurant serving regional specialties. The protected area around the summit is also home to rare plants and animals, making a visit here truly special.",
    bus_route: "Walk to Kriens, Mattenhof station. Then take the S4 train to Stans and walk through the town to the valley station.",
    tags: ["view", "mountain", "hidden-gem"],
  },
  {
    ...BASE,
    id: 54, slug: "klewendalp", category: "hike", sort_order: 50,
    name: "Klewenalp",
    tagline: "Scenic walks · family-friendly · gondola",
    address: "Beckenried",
    description: "The Klewenalp above Beckenried is a family-friendly destination offering magnificent views of Lake Lucerne and the surrounding Alps. Accessible by gondola lift, it offers idyllic hiking trails, bike routes, and barbecue areas in summer, and a small, charming ski area with wide slopes in winter. Cozy mountain restaurants invite you to linger, while the relaxed atmosphere and wide range of leisure activities make Klewenalp a popular destination for those seeking relaxation and nature lovers.",
    bus_route: "Only accessible by car (large parking lot available at the valley station).",
    tags: ["family-friendly", "mountain"],
  },
  {
    ...BASE,
    id: 55, slug: "lakeview-biregg", category: "hike", sort_order: 60,
    name: "Lakeview Biregg",
    tagline: "On foot from the apartment — insider tip",
    address: "Auf Oberrüti 19, 6048 Horw",
    description: "Start in Nidfeld and walk leisurely towards the Allmend stadium until you reach the Waldegg Horw bus stop. This is where the idyllic Bireggwald forest begins. The trail leads through a beautiful mixed forest up to the Felmis district, which is picturesquely situated on the southwestern edge of the forest. Continuing along the edge of the forest above the neighborhood, you will reach the Seeblick Oberrüti viewpoint, which offers a magnificent view of Lake Lucerne, the Rigi, and the Bürgenstock. From there, the trail descends along the edge of the forest to the Tribschen neighborhood. Here, the lake shore and small bathing spots invite you to linger. The route is around 5–7 kilometers long. Return from Lucerne station with bus no. 14 back to Nidfeld.",
    bus_route: "Start at Nidfeld, return via Bus 14 from Lucerne station.",
    why_we_love_it: "Take a picnic with you",
    tags: ["personal-favorites", "hidden-gem", "view", "lake"],
  },
  {
    ...BASE,
    id: 56, slug: "ship-to-buergenstock", category: "hike", sort_order: 70,
    name: "Ship to Bürgenstock",
    tagline: "Boat trip · panoramic views · funicular",
    address: "Landungsbrücke 1, 6003 Luzern",
    description: "A boat trip from Lucerne to Bürgenstock combines relaxed travel with spectacular views. From the Lucerne lake basin, you glide past picturesque shores and mountains to the Bürgenstock station. From there, the funicular railway takes you up to the famous Bürgenstock Resort with breathtaking views over Lake Lucerne. Whether you prefer a walk, the panoramic terrace, or the spectacular rock trail, this excursion is a highlight for nature lovers and connoisseurs alike.",
    bus_route: "Take bus no. 14 to Lucerne train station; the boat is at the pier in front of the station.",
    tags: ["view", "lake", "romantic"],
  },
  {
    ...BASE,
    id: 57, slug: "ship-to-brunnen", category: "hike", sort_order: 80,
    name: "Ship to Brunnen",
    tagline: "3 hours of pure comfort · alpine scenery",
    address: "Landungsbrücke 1, 6003 Luzern",
    description: "A boat trip from Lucerne to Brunnen is an experience that combines picture-postcard idylls with dramatic alpine scenery. The journey takes you across Lake Lucerne, past picturesque shores, charming villages, and steep rock faces. Along the way, you can enjoy views of Mount Rigi, Mount Pilatus, and the Bürgenstock. Depending on the boat—whether a nostalgic paddle steamer or a modern motorboat—you can enjoy the fresh lake air on deck or relax in the saloon with coffee and snacks. In Brunnen, visitors can enjoy a lakeside promenade with views of the Alps, cafés, and the legendary Schweizerhofplatz square.",
    bus_route: "Take bus no. 14 to Lucerne train station; the boat is at the pier in front of the station.",
    tags: ["lake", "view"],
  },
];

export function getByCategory(category: string): Recommendation[] {
  return RECOMMENDATIONS.filter((r) => r.category === category && r.published)
    .sort((a, b) => a.sort_order - b.sort_order);
}

export function getBySlug(category: string, slug: string): Recommendation | undefined {
  return RECOMMENDATIONS.find((r) => r.category === category && r.slug === slug && r.published);
}

export function countByCategory(category: string): number {
  return RECOMMENDATIONS.filter((r) => r.category === category && r.published).length;
}
